apiVersion: v1
kind: Secret
metadata:
    name: github-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:i43yWyePSzhNpOBNC5Y9UlFMv8iUWvlKhUWbGjkXQoU1eR2LeUMyV9sxwYqM436twSh9HNoZM+p0j5g3YLa5QzBkA9OjfILzWEhM+7dIh1te0Q1aGQJMAsHBMfFW,iv:IVAyFb+hTSP2Rl1cMgUJ72evRm/VjnChuCPpaZCpioA=,tag:lRudwHTtYYkeGfZ4xkee/A==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUwyNlJRQ01uR0VzQkwv
            WjVmRDUrbCtUcTRWTnZ6eUhJNmgva3hNcGdJCnNOYzNaL1dBdUVwR2FYSmlmOVgv
            WlFJMHVmVmhJR2xzQXRud2RYVmpiekkKLS0tIENTTjg5QjlOakFaMjNtTkplUXdL
            bUlGVjVrdlcwQm92L1loN3IvNjdFL0kKoBU4T5LEeuR6LxRL9xoZ34eR23JYHjBX
            8dKbd/eIROtjJVIzQRuxWcfNAR3misuChgu6+Mdx9pxIjfvtO9VVag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T18:48:36Z"
    mac: ENC[AES256_GCM,data:5pWAAFmsTymBxf7tM2R+UrAIsd3A8UmteFi17OQKddVHNtVRXqlsFfOWxy3Dk430zxGeIw5XY3A0CvbBj10GwD0y8sNqEQR/ui/PwTtAVJIPzr/eSzDyJicvjl0XGTN3MmFp5jGKFfH2qCVuViR3YgVDpTU3OaCupROvDrVTry0=,iv:9obDpCthkN3jzBn2PJr0SJQL/G2+69GoxGIqHWGcPA0=,tag:P7tvt9c/H9QYNggImgkvdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
