---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - priorityclass.yaml
  - gateway-api/ks.yaml
  - cilium/ks.yaml
  - descheduler/ks.yaml
  - intel-device-plugins/ks.yaml
  - metrics-server/ks.yaml
  - node-feature-discovery/ks.yaml
  - reloader/ks.yaml
