apiVersion: v1
kind: Secret
metadata:
    name: netbird-secret
stringData:
    #ENC[AES256_GCM,data:2ha0NFDmI6P31vTbefUKDW+zGnVTBFkIhuseE3BZ8lCztKCCKITe,iv:k69QOnpNd4MXY3dDG9hVl67pJgEg9e0yT4aCgtcHUcM=,tag:1C1YkDZ4LQOOzPeOl90b0Q==,type:comment]
    NB_AUTH_SECRET: ENC[AES256_GCM,data:rYTUrp/DVAp/XS/CuDp1LgCHJBsXJrWgCMtFJv8DQ+aMH13bdDUynEk7vQ==,iv:2/XXpjsatY6GNfgpWpxLWndDZZAPHzdgsireABkWT8o=,tag:BuOLHUIDsXl/eouDUhaciw==,type:str]
    #ENC[AES256_GCM,data:FaPDkQ8V2Ef2NDHpZFw1lmR4uhb4Yj8A,iv:ni/p++mPgIzoNPCBR6dZgP3MKBz+NTXZ0knyQiuWUP4=,tag:3ao/6FIeoqaeb4OmTWKUow==,type:comment]
    DATASTORE_ENCRYPTION_KEY: ENC[AES256_GCM,data:ycxaOXDP7SagL6fohW1Xev62JPLcPzP72fFVfSWV+BHqdC9+HuLzymN7pCw=,iv:SqbDGjD9pModutBcjATCMb80t9LGj9/ToVvhaq5IBkM=,tag:2lrp8mTGHBW1w8xtPQRM+w==,type:str]
    IDP_CLIENT_ID: ENC[AES256_GCM,data:g1chDpUkdw==,iv:9uVTJkDd/3k813PsSAZLB9daipCfGwIQu4DKXQcOYGo=,tag:mjUOy0va6/4e80qsE8IHNg==,type:str]
    IDP_SERVICE_ACCOUNT_USER: ENC[AES256_GCM,data:ogRDIFp02g==,iv:59gZl9xm/E6bmzWkBnTpFEEM1YQSOUAB3LlmUlkGvUg=,tag://hBpbbRnIWY0KUrECrcmQ==,type:str]
    IDP_SERVICE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:MPdRx5k6rMpxoj7EePQEzO6Y+i3UaqDXszYeUO4+L94HczHlZ2IpX/zBTzHzoDVXznN8shI3Clc0lnJB,iv:BYTzm5lcTQJCXND/Rlqh4wA/++dxoCut+I+/vA8Bm98=,tag:bUQbq1zCSVsFn9Cs80sTPA==,type:str]
    STUN_SERVER: ENC[AES256_GCM,data:ms1tAv6mbhr5jSsAFeYXVV0iDaPi1u6XO2cgAg==,iv:3LXOZ5egF0faMNLdlyWp0OvUOkqGK/cnXgoDK2tTiwc=,tag:48G+IHi8+gvO/R8dcx9sog==,type:str]
    TURN_SERVER: ENC[AES256_GCM,data:1fGIX9sGlFHk1qcPFma8+AXJItBqvIzbyqnWUA==,iv:kA0Ibx5j1HE+MqMWZjmr5uXRvGnWpfS5+fvNbMuSx4M=,tag:9+Pp3wX2posSjkZnWU4sKQ==,type:str]
    TURN_SERVER_USER: ENC[AES256_GCM,data:HUl40hydVXcH/xBxOebrMbfxx9AvYKJl,iv:gAdfUZzKC91B21BGT1LjzIouTaczjRXwAM/iHLCVlb0=,tag:PkGP+Kt1gtLKA3XpXF47SA==,type:str]
    TURN_SERVER_PASSWORD: ENC[AES256_GCM,data:vZ8nzR63t0qqmwTK+hTODl1Hxgemx+zVNk6Di/xXOjKoDrK8D+VyOZVGcqFaBkMSedDeklO8bWt2sbLXUAU8Sg==,iv:lBdP0yFD2I6ZcqMAOnjE7aoslsIQgiAzPwCG6J6OTD4=,tag:/tA0kcC3xMEPrV9+hPoi4A==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbmtqKzBCWFdGQUd2ZUFU
            QWtBeWEyUjZzMkdEbTNWOUoycDZveVJhQzNjCkFKWVk0U1lZNllmNVBzZzNBeFM4
            RUwxa3RObGJSTlRwc3BrSlRlOWI0eEkKLS0tIHpEVGo2TFVPZkI5WVJ3OEJXelZz
            czFwSW9nQmdXMkRSMnYzNEVZV2RrYnMKD3kE4GVOuTVF24tvKiJdyU3ypE13oZVw
            D3/pn0sg2X9HP8MPlVPys7ow0+8O9hmZmDG5BdXu2wyNHoRh6ROK3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T17:24:01Z"
    mac: ENC[AES256_GCM,data:kWiGeW2FTOVOIVYKnFYLDEUTsVVcXmv/M2h2cpQr1Yypm/sXGnqe/6OMLVBLpWOH9WvFuBs5i4r60bOuAReqRECUuCENK2yGQmRVqB9ptfuTa/V77wo4xyDuD9KZIfNgvxBGrmthogxiTgaOnGlaLrP9YE125bbkNkOJ9KIDoBo=,iv:C8y6MpLOh2HLLsgXwDgqQ2ZksqBuWOIQUhZ8+P87PCw=,tag:BYzUa0ZTAqtyUGDG6xyT3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
