apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:XETWEy7lnhovzhqhS687Ig0yLaAK+Zm8jZN8yu2R2W+X31bP/U2vSjWBRjORBw==,iv:RFL2dXT6tJWg3+Phb1TWjIKbd0bQyqMxvGUXNMlSm18=,tag:bx6Z4pAFHcxpfbDgladGRQ==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MW1yMGphbTdVOVByU2pD
        TFVxc1hCWnN4SElWR2JSNGFWdFVUekNSd0FvCm9kVjZMQUhoVGZhVzVWZldzRVhD
        eDNHbVZuM3BScnYzQVpPblhvUmZDak0KLS0tIHkyOHNmdzNCbnhxeEdmRlgzTm15
        T3kvUHk0TjFkNVVZTE5OQk5tNHZ1TXMKs2wBb1NylGhLb97c1/5mMIyGtEMbp94j
        SKvdm2w7v8PQxbZJHQqKE9tDMN1pCjqHYHbIzFQ6unq79EtJKa9wbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T20:28:42Z"
  mac: ENC[AES256_GCM,data:5wcc+Tiio3P062332y4Rs8wTfyKKPUUFKjKU8Ab81vEw7w4bbMFlXBRwAxxYyzqTHH0uqELMoqT23krisqR8UhFRAI1LNCJssJs+imNOQw4Ok/OXySycxLc7az/bDahEBMcIaM4trz5CwpaEIHE2Rse/h1mrV4RKPkNZgtrJu4Y=,iv:EeEu2Dq+rWfz+mdKTKPYHmVwamtutsLZAY0OxhINs2E=,tag:iwT6R+Ggect3NaenZern3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
