apiVersion: v1
kind: Secret
metadata:
    name: newt-secret
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:JtY0lSeLG6zUEaXvJzsMzklZPYZ2JfvgrdIKpgNb,iv:zJEnIKp+4srGj8wm1UnSuZFNK2+vXici0o1MHMjUBDA=,tag:2HUeNFDvHo8vKSAmoGipVg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:VfzuGjEIjoPdHsW+46l6,iv:y7dIHxdfLNuLuQDiZr1HQ9aDs8yZ+uHGE/GfuHgmzXI=,tag:csnwJ5eIhvp/YxxrZBCaLw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:PPuPnwhFxAnhRPVEiRwakuhzNgFuw6zuIXett0EV0rfhU1DDsyo5FUsQvKlmwwi8,iv:S3lC/ZqjoqizfIedbY0c8/ucJZq1g3uuC0CSOxna2I4=,tag:YH5MviX5BPyy/WaAVglswg==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFJzUm4xQWtsL3dQcjM5
            Qk4yU2Z6TjArcytRWHUyalBpTHZiTWNpbVVBCkM5OGdlVW94NGJRUEV0alNrMzFH
            Wm9VTi9yNVp2M3ExZHZjd08xaExBVlkKLS0tIEhaOXk4NTY1ODlNSmdQOHp4SUpT
            eU9KTWZ5ZkFuNjR6RTJiVFV6TGVNL00KmAc0FaBGSUgZz0lqmumoBDEWhzQsydEw
            d7axAWAfi9fe83rOYKwvOzxYO6Qhgjrjq2CAl1Alx2lgtdUvBghCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T20:03:49Z"
    mac: ENC[AES256_GCM,data:L85/0bJ29I4vwdFyIR5vJO2Lh3IbjSgKH/90rNH/u2gU1mVb53EE2xs2anHwtdTRlTTMoBqO8js0UHnTo+gvbpob51cvyvBWzlNTCpttFN+g1AjXbGxN3BmT6yJmvBSNJH7g8jtHj1cFv1yFF69NSOBX4xeIGq4K0b1YpNtTx98=,iv:W/L0mXZSBTgmS3vxPpALS/XUhDZ1/FSGOMjqp+Zk2YY=,tag:wz+fB0FtjP2sokYxKeiNLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
