---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden-database
  namespace: flux-system
spec:
  interval: 1h
  path: kubernetes/apps/security/vaultwarden/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: true
  dependsOn:
    - name: cloudnative-pg
    - name: democratic-csi

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vaultwarden
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: kubernetes/apps/security/vaultwarden/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  dependsOn:
    - name: vaultwarden-database
