apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:n1G8ymev4ue4Iq0uak1v5tvAAg==,iv:t/P4jZxcQA39w0h3j7mHsaBcYIV2qq6ViWtZeZruDe8=,tag:OlypWt5nJVWMVoihbhKmjQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:h2NKkQU6KI7Dy9uivw==,iv:kIuO+hN4FEsBo2CuhEEUCmDL8m7R8FqBcV22wc86k9A=,tag:LfPm7hD/yuUAKWfAnNATlA==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:OpJbqYNxBsGW4absFGxpyA==,iv:thk9SxAvwFyAy/G05kDT3P16k+a8RwpF/39w1YYPqlw=,tag:LgXb74oVz8nUOgPzX4P6xA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZnU5U2UxSTMwWmFUdmk0
            U2FodWhBRXhnU0s0dXRNVUNOV3pNNmtiRjNFCkdJVmZoUGpPd0V1L0RzMnp1cVJW
            K01GbDV2NGJZeUxzaWxVL3JwS2ExVFkKLS0tIHpBK2xoUWQ0T3JKbkF0eUZ6NEc0
            VkJEdERRV2F5aVVBZHArR3pHRnZGeGcK9cx/f7XRgtKGg7+cpavXcVJFwiuQgqFK
            2Y/DI9HLx83Vt5whgoYFOC8A16/TMa8ywiB+B26miH0O5YHp19UTvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T11:49:22Z"
    mac: ENC[AES256_GCM,data:gFtB5O4zc1+YYdY9HgreEv7V6eaYNp7jOJEoSbwhD5bBm/kej3Y/Hb24cUQVlMwolAYl6TKiXbr2C1zxYxVkPEt8zt2ihr+4vpiYQGfakSZzEh5Pgs1WjJAkYlOAn8YWD3YswU2Zpr66QBezD7b33iLnp3jwukMMn798H7KmrwY=,iv:qb/gtAG4LpTdFVFKPDokjYMxrTbRiIbLRsJxjJ4C4x8=,tag:+usxa3ijPEJXC2FLUVvhgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
