apiVersion: v1
kind: Secret
metadata:
  name: autobrr-secret
stringData:
  AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:NlsK3+zz3gkTpw6hclbUFBuY7EmZxXCNWlNrGdUczYGEMhd26Q0MhuYfXQ==,iv:otpePVGkpwoavVczC7o4oZvzrCqta+fXG2etj4GwuYc=,tag:6AriSWXHrNsiU2savohIOw==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdTYrRTlzS21aN05OWURl
        Mk5yM0IrcmwvNmNxeUNJSVNWdzFpWjFpeFVzCndUNFNjcGN1anNnRk81OTlHcUtB
        cDVzY3Q2RlZUa1BwZ1dJd0k5eUkwSWsKLS0tIFhYQ2I3Qkw3VU1LcW4zYnIzQi9o
        WDcxQ0tnZkN4RlQ3dGZKdkVmR21WcTgKwYUHlVgxxCaUsb8x8A/DjFtETZ+fbDlK
        6i4TrgmundxaybH408/VciG/6CABLkdz4qhReR67GPhnadk4U9ienw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T20:20:47Z"
  mac: ENC[AES256_GCM,data:bkaBbEixsnwpCkmgGxeIdZ9PRiOl/0lSEjL/pbxzEijPGEeFMGbc2ifEsYC6UiAsxDycmznYR+nmCK/DSA4pXw1wGFeU2LlVPUP9yhETYpmycGI8vws4U9MwPDbw0wUFZNB+eVzVop9R5jG8hus5lJCVQGX0Ttyie/vlQ8iZLrw=,iv:kbYShKG1SH/bXqP4nfdfAQ8YtfCn+y7g+lG5UVxT/i8=,tag:wFZI6o0uGrLhAobejCDFbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
