apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:HzZuJlfdQLa8MW6R1CS2nQOMrNVFA/BKe9/A1cLX4uGBJY/t+u29wJKmytrVfH8jnkgo3achZzMo7CpYgjiL8DffbTn83+R4N5VWNZX+6uL63Z8gt+TdVUlEpbiuS9ufMefR+AXVrcZlEpAPLJEQIH5GXPzbMg==,iv:ORY4jysvhvPwqsNcYNg3vHO/WcYwGQPotDaV05niA0c=,tag:ZH/m/Os60iQtLtMyNTv0Rg==,type:str]
    SSO_ENABLED: ENC[AES256_GCM,data:pzv9Bw==,iv:VxIS9py5tboHdohwFb2xktw+SInlHDCPZp1Bmz3Xhzc=,tag:sZsY6PBLNVb2dSlZ3RmFNQ==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:jXjo1nR7tAz6Qg+FaCeVRIKZDCcmRvZPwUUGWcMbFoCxtNtJ2L2rMHidWoUNkKB2wq6fgGXtBmI=,iv:G0kxcUbrtsh4e8c5uVbcLr/COa2XqcsWGRK3Yzi0IQc=,tag:gyt+wCpYwn4kWGhALuF3bQ==,type:str]
    SSO_SCOPES: ENC[AES256_GCM,data:mQWNO9xW4lPz09velqYI4y7qIifZbGxLj2YtgUDm7tg9wHc=,iv:4eN54rfUhtjxE5nUoCorjiLbOJbPfe2TlA3OIfFb0BI=,tag:RGNuUXGgZEONEd20l2X1uw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:AMOW3sBbSgZYMFxBAV3fcip7fskMYnbCambRf0TGtmr3FzwlKYpO1A==,iv:9nwbCVz4VeT4gIiCuAxm87Rax/rFIlt6gSFcOKIBiVQ=,tag:wgmQD6XrYuZjwSixl9YplA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:IdEdt3AD9gm+io5S1F1mIwi3x/lz/dSJTWv4wW7kiQW6/SvB6Dto2NeMbKkee+9aW0n0D1xFFJ5GnoZBLmV9QvmxAVo+/ish30M4+9JzhxRZLw4OQvPIj5WdZfvx/z+Vo1K6Ox/TiwMYmYwlSFPHIuNPIRwVbTwtEOMq51yjU1k=,iv:AC2oKpXOMr0EPPlYUdU9sn+K2vXYqUBMs10Vj8k4yKg=,tag:76Qfy7dp5bdpi82TKnfQXg==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQkYvZDd0NzdRRjdaazZv
            dE9tWEVlRndIZnlxR3I0eFdid0EvcEpNK2tBCjljWGZ4aGx0TXNzT25KUS9OMUtz
            SXlBWXJHSnNRQ3lTSjBuemQrQlZoR0EKLS0tIGdyV0preEVDbHZYWDgyZUJaNnNI
            bWV5YmQvV043QllCNCsyWkJFSTlSdFkK5t1s9zOnkUwbQWYio6BsW508/Rdf7Wa9
            cenBg97dIQ25S324/7vukDZrdkM/k9z16tpDDK5/cPZvKHwO4++2zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T08:00:57Z"
    mac: ENC[AES256_GCM,data:gtFzu5K150zPMUQxnimMAZ0FbkIX/nb4MBYQshsn6Fmrcwbbf8Fb/Xin+n6pl84jSiZ77uTGWdpiXIGB83PmpH6TSdul/QlpnPVq2Sf750AgTxOTztWlKPb1DyM6naNUHO7VH3Wt1aOr5Es3J7NFj3dUkscGS7/y3OdjwzKAczA=,iv:yK6z1mRFPTIa8pr7v8W1lrX0hBrfS9XTivPououQbWQ=,tag:SO5FWtcbjpn8pfv1VGP5NQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
