apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:86Tbnj11FQwCysKmA1f0qbWDl+0F7sHiGAHhw3gcoJMQCWi8KP4OeMk1NL71to5Y1x4hHwAgzOsOKUI7TtfDUMoczU/7VWYNjpESU0cOs5cwhen+qtoCuOqB7OXgUxyBzMOjqeD6OdEN0bxVDGxfkXvVQ/blSofPLF1JZOfM0ITjbl955X8ZqlQMXlWKxuFncN8nWIDA1V+82kdBbQrW6+9si1dGI2YlpMB9011Cx8hJbTawm+/Lnw==,iv:V78VeCMl2njYQXNJBU2vrEMTvDLJuSVlvBwhDOPKeWs=,tag:dEtXfGznDlQMQI7vPNkEpQ==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFJzUm4xQWtsL3dQcjM5
            Qk4yU2Z6TjArcytRWHUyalBpTHZiTWNpbVVBCkM5OGdlVW94NGJRUEV0alNrMzFH
            Wm9VTi9yNVp2M3ExZHZjd08xaExBVlkKLS0tIEhaOXk4NTY1ODlNSmdQOHp4SUpT
            eU9KTWZ5ZkFuNjR6RTJiVFV6TGVNL00KmAc0FaBGSUgZz0lqmumoBDEWhzQsydEw
            d7axAWAfi9fe83rOYKwvOzxYO6Qhgjrjq2CAl1Alx2lgtdUvBghCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T06:38:53Z"
    mac: ENC[AES256_GCM,data:DmdqCh0F1Iw6XLp9PKB2DfM4/iDNktl9cxj3A2Wf+NvZnYqrjnbr+lEC85W29bomPFFAK2jgsSvxtIeGPFKCTpE8sKnXqU2cA/y4FyNaCadpXAL36hlOBAfrvXkz5z5mco1S06d1zY3lRR7ToiCajkladiH4DxlwDcNVmKvYKZE=,iv:vcH1rA4b7vtrxddG9mEN19jI2UnHDc83EyB3aL7aXb4=,tag:boIsaVQJPvxjwNR8grsTQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
