apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:PWFGvDEWalCfYIs7t6JfQomJ1fVsWLYU382DRDY4XRIaf/2jmygnxg==,iv:wKsAGz+VDZm2dTMlwhfVIrKPE1zH2k6ml8JtBXntOXE=,tag:+OK42wvOazDoON5alwgouw==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cU11N201R1JtTXY3Mjdp
            aHJ6RU5ZQXZ4UjhHSjgzNTRLVDNrbVVTSXc0ClBUTVZWQWI2UkVNdDRwVGlxMWVX
            emJvSkltMG9PWklWMi94QnE4R2V1b3MKLS0tIGJ3cFNNRzhiZXVJMGh6c2ZjSzc0
            QWdJeXpGUWJsN0J0RlZTeGl4WkpMT1UKXc4uGpWLExkU7wDp8CgRwf2eOP9P9LYN
            yv2q3wb9fVy7o/9NxnT0zrBB9I7dsCnlg+RGf14UXKF2XJLUCrhFnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T07:06:06Z"
    mac: ENC[AES256_GCM,data:hLziQcHFmGwIR6g7y8r9C3rgUn9o5oPaHMPIDxarIeMlD3vl5QiQASuqapStavCpoOWp4ZMBe9WFIqq2sSAayXGF8INULUQ6f4pX7dS1ifpmyVmnmuZY71UANaqO+ejxarnkkGUAJjPIV9KYqZB2JBHNbvC9FsgQeKBXKXImGyY=,iv:oZGJ/IkJ41VXxfbzVXgJoDuKgJ7q1cYeBiO4khsZruE=,tag:8lgcAEq9Eqi3tLCkOTjG+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
