apiVersion: v1
kind: Secret
metadata:
    name: netbird-agent-secret
stringData:
    NB_API_KEY: ENC[AES256_GCM,data:n0Ag33pcprEDqvy7GbEXnZFJBQsxeOG5pIHmwgjRbAXzUiXoT1ep1Q==,iv:48mjfHxyKkNlAgE74QMQm3Cf7FC9E2LpNheMhrcPZro=,tag:TDQDIwZpnVJkK3MNIT0SyA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbmtqKzBCWFdGQUd2ZUFU
            QWtBeWEyUjZzMkdEbTNWOUoycDZveVJhQzNjCkFKWVk0U1lZNllmNVBzZzNBeFM4
            RUwxa3RObGJSTlRwc3BrSlRlOWI0eEkKLS0tIHpEVGo2TFVPZkI5WVJ3OEJXelZz
            czFwSW9nQmdXMkRSMnYzNEVZV2RrYnMKD3kE4GVOuTVF24tvKiJdyU3ypE13oZVw
            D3/pn0sg2X9HP8MPlVPys7ow0+8O9hmZmDG5BdXu2wyNHoRh6ROK3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T13:52:49Z"
    mac: ENC[AES256_GCM,data:4wo6pcrATbBvjYZE//+dGTZPcPVh5il4C9pheOeo0B+rduuXsbFXEP3UP15OnSbMD9Ho0HH6BybmdUMyejrp2Zni4T11PFYRmo7ZM9XIS9LufbTr5mC1yx6rPo8/joAYA0Rc7K7eWSbRtP8Rqm8P3TXE0lLMap6CeqLmhYMtjWY=,iv:MufoS0Vxe33Ucba/wUGY3mnXVB0vtEZWvSjq8PWzB7M=,tag:5lQZmTv9Y1xWkjvVy3NGVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
