apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_ZONE_ID: ENC[AES256_GCM,data:vUpF9pbvpKKnqY3BpBBrayVBx4YyYuK5BNjgEI2mAz0=,iv:sKwvG96Bg9ngGpA6oygwpgvwOfTcUgUCL5AsfK/pCBE=,tag:/19OR4vft3PHI24HgywGeQ==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:DRzSjlyCxd7ME8aTUEqqOsyFPifyfBxbnkTHll20n/d6zZ8gVSn9Ug==,iv:VVzDnAvCYgbLDBGHTXlfN7P0wKQPrZhXz5kMF6/N7PE=,tag:jjBOtdIKJBpCaiDzHM4vXA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFJzUm4xQWtsL3dQcjM5
            Qk4yU2Z6TjArcytRWHUyalBpTHZiTWNpbVVBCkM5OGdlVW94NGJRUEV0alNrMzFH
            Wm9VTi9yNVp2M3ExZHZjd08xaExBVlkKLS0tIEhaOXk4NTY1ODlNSmdQOHp4SUpT
            eU9KTWZ5ZkFuNjR6RTJiVFV6TGVNL00KmAc0FaBGSUgZz0lqmumoBDEWhzQsydEw
            d7axAWAfi9fe83rOYKwvOzxYO6Qhgjrjq2CAl1Alx2lgtdUvBghCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T20:48:37Z"
    mac: ENC[AES256_GCM,data:LRoKk/bslCU1qBC8q27vdWAAZplaVmXBkm/C4aWVCG8Mh3Vc5BbjyAPNmlXvKQB/W9EfJhpA1WyWvwdAS5alCiy9WR6dzCyzBCVDSwEzdjddvfI9gfWo2NL694JnavFVSFDeckGkhwXf0D+yrk5bFanO0GTWSJsViH+no+5K/HE=,iv:dwIjc1eX/AiqYxY2zmLnOrvx0H/so3QQublyGXHCJzY=,tag:l26b0/Ul3dauyaubzEhcmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
