apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: observability
stringData:
  admin-user: ENC[AES256_GCM,data:AYyAo8o=,iv:d0fklzzeVn0+7rcFnDXxNTXUn4C7D7H44BCSghZSHX8=,tag:fEz3qc/OiB+APtkcepcI7w==,type:str]
  admin-password: ENC[AES256_GCM,data:1Z8YZyXw3rabemEKupA=,iv:NJgn3qUS8LGTm06FE0an43iyehKX7Zf+1c9ggroW+P4=,tag:5HKylB71XW8MdJE1BNwhRg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRem5scC9QMlNLMWlaYjJO
        TUI5M3dkcUEwMXU4Vzg4bkVaVVNCeno5akZNCm44UFhsZlo5dElPeVdHWnRFeFAz
        aTN3bmwzQ3ZvVDdKTk91SEF5K2J5d28KLS0tIENjUEkyeTkvOXllMzNDTWFKNkc3
        MDZTQkxxVjh4c0JIS0FmM1NPZ1Qyb0UKKVwKGEqEs7AIuRnueHvYRSI621Qz0DxY
        Fz8X8OVYtSDS6onvgVKgC+WZ/FLWYx9EzwiyfL1JZENxPyJVu4Jp3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T17:20:05Z"
  mac: ENC[AES256_GCM,data:EbV7NusRrJiXoXzH9uYW0khFlb4ovWurXIilu6atZkb2YePVcufn9ns/v5NM9DxQIhqQjpZiRVMpwV89nk53lX/L2Qo1r1j+OFSFS4nmHeyTgjfJv5c9pCrNYlROGKv9brgNOtc5ddZMVY2IkIS/mVX5rkcipWrWb3cco2VT8H0=,iv:BOPI5RqYY5kgeynf2375wnsveYHomuIirlhXYcwfcUE=,tag:Vuqsen14VrjWiwphZQ/eeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
