apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:NIPJrRMTzLuOE8ZS4HzBIMX3a6EUIiQjN0WrIvoI2UI=,iv:48q4tFa4rvF4H8nOgEJlB9a1ne9XFTs3S6ztMsoo0aE=,tag:mfzChg8GTROQyPoaqAvEvg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYXhhQ2lTKzlJL1RaQ1V2
        UnU4MzZxbmtuOHNBTVA2di8wMTJzUStmWHlZCkk0TTU2WGs0SWVkbVRWUDh4OGJv
        cUg4U3BwQ210cnFURVJ4YmlENjQ1bU0KLS0tIGVCNmk3ZmxLMkJZVWdMbXd2ZWN3
        YktWNGE4clNGcHpLdVB4MmRXczFwSEkK+SFFI5unzwhaHf/spHQrxMOg9nhT60xm
        EWDFa0UJv1M8i7JaNzcu/aXjjM507O3FC1H1iYnUxiwiIrPeK78nUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T05:32:44Z"
  mac: ENC[AES256_GCM,data:3OGHi5udACwIbGZ4pNcQ5z/2vCfWg8Li9tuBHVX9xctedtVLMSJxbZmURDaPaYo/qXyNKlj1EB/fduDPNcrR03CI9EWeTEtn/MrzKzARDaOABu9cR2cFQeScI/49Gs1eFyL7YKHclFMwCKme10X2JZoqN3cYGEcoWvItDofZVLY=,iv:RJl1uOiDLlr+gNq0Cwtty2F9Nn2hEfpr2SmHQWAWexg=,tag:gEhsT/T7iNZUtc/X8Wonrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
