apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:epagSFlIjiwJz4OilugW8VF2LA==,iv:GiD6na+r1B+SS77JsIcQxZvz9+avRSCVGOllEkjmQZE=,tag:ZQC2+34vv6O2W5Qwmwv7LA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:kjy05ISujDhkYNBqkj5T68/kammXvMiKj5fmV/Kbs3y8HG4RjHa1EISOJLZ4zMgu2tDipJjMq/s=,iv:Daxi2L9fHJLJWKYunHgqXkox5A+qbu7Bwk7HIeTPZu0=,tag:PgOntjsA7UA4LwNPnzqpQw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:HQHb+sXApRlNtInIVbzURHN8oBXbKBFi1gbF3RewOx66qYaxJADch00M4w==,iv:I7atD2aoTcq9kCPtUu72liQ8+gdHEaMuACMUS16SWNM=,tag:zj1257Kt1rXm2yoPzVIbzQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:k+8I+hFwmuTYy6xoj3BDyeYNe4yYow/7HSDEQywkH+USJkqPPpNWxTBhQ3Bv9s/e23YPNvt+0jGgTngNpzmEceFVqjeUQA9LCvdnIFHyEWM=,iv:h9ydfDREBgjxa04vit0aY1VrgpMp37NvwUb5/qKI1VI=,tag:pd5gKXOX4TRNFtghHY4lJg==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlI1V1Vra29tZXpoVDZq
            Q3g5Ty9aWGJtM2FmYk9KY0dlQ0tZbHRvN1V3CkxuVTVVWEVzU21LTDRUR29iUXpN
            TG1YVjVXM3hZMzFFM0xicDFJM1dLVlEKLS0tIFE1TzlTSUlDZ1pibkVuK0FzQnAz
            YmoyTU1RY1p4RmE4K1VBSURyblhEbXcKTvvIQW+sGq3PsR9mtw6EtHBmCqmm9R8/
            G7YVLcOiNfsZTj87VE9xtrnzL5iRx1XN6zqoCTEbSgK67jul4HmASA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T20:47:33Z"
    mac: ENC[AES256_GCM,data:HSlgxqOAC3uuYi7mnr3/GTny29L90VDsU9Rthl9OgzQfVKftvKcItqb+dVJe7KPeDUIAAtSfIXNAT0Z/5lpJDLC0o92pxneq/wCd+2aKmYBDrYQAYteoPw2f+C3fYNxVZ2/i13oNSzFjgz+rsEbmAuKYIVTuh9kj5Tmx8Cma7dY=,iv:JZTBATePuk8USQIZactn3tPhBj6394KpZf7sTaOI2Q0=,tag:P/9g4jSrcmG/yuKPN2EehA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
