---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: kubernetes/apps/comms/matrix/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
      - kind: Secret
        name: matrix-secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: comms
