apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
stringData:
  api-token: ENC[AES256_GCM,data:NggPaqBv4prnb9OK8la7Ulf7jnRakpJVDX7E7uvP8+0IBHH/MOJ9Sg==,iv:zv6bcc2gXGHAkfeW+uPVwR7cQjSON41jNLsgvQWwDmo=,tag:VqHym2fhZLtrVm7+6uctiw==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWFlIaDJTeUdoSENuN2ZG
        R2JTcFdWaGhWNWM0dy83Z0o1cCt0d1RjRUNRClBDN3pnam53cmFsenJtQUhzd1pa
        SWJUUlhEVUJjelhic3djNTdHVWNpM2MKLS0tIDllT0RySWkzWEswQXpiRnBGbEEw
        c0lSQUEzWTFRTVhtaGM0Z1NqNTNKd1EKQjPhJjbo5N1r5oMpDXFmhGERIjAyMcNy
        7w62SCYggvF9MCF9Wi935hC4K5gfxsGzoy8RC0XXeBusuCEqT1egtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T20:43:21Z"
  mac: ENC[AES256_GCM,data:tblc4dZ2Ju575y5vumNXSOhlMFpv5kSW8Q2vGFRRmJagO2f7VIxO/5kPYfQw1p10hifF+EVa7pBh6bSdko13CN6UX5sjuFrqQ9NTT4AR0G+Y4uGbVo7JtE9R9Dl2gkShkx15N7SXyPbN1PJ/zlwC8ae0QjPt58oO/YHMVA2Ef08=,iv:nqLHD7Mqw6rtU3CHwul65GZ07JOhdwBZZ0h96zd6q8I=,tag:eu2aDE2S7k//KGyRLu8c1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
