apiVersion: v1
kind: Secret
metadata:
    name: komga-secret
stringData:
    application.yml: ENC[AES256_GCM,data:wyWf1CA5SwWWAYy0b0Cs6XjQRPFJZigbS12hcGINfY6PFldXGK+axI1OlVUUIKqVkybf5rjwI8kKqccPq8gEE0ZNSmdHCAUydPBf7dbEiWcMq9B01LXmO914fFVrzdGvS+EvG//ctveNkTM4Gao41KIwO77vOVqp+F/PeQ6Z7S94IQIZLGi7O3fCtJaRjdkHT/zqScfmZiKrw1l2SPHo2kzFiO4CF/EA76BKdFnp4go8zFhm1vDwRTzii2KSLVukk83i4v56GMPenE4plqd5xPDMWtwSRslM4EBdW7Pfim/6LUkTjyTjT6jNGwpkAX4uolWb6C45rS+8ibxHTECSslZQbvYontLIbblc09/gn3nw9w7F3z1XgSt3vjG92vxwV97D4tb0Q9qA+VR0tXkpFGKouyG3Z5iY664Vip7CB7XtZtelkfGntRtRUNkeMAuhro1JaQm9sfrTSVBZniC4jMqTjLEmEUECq+G7yCb9sUdS995lUberRJIHrfG7hbQkNyVEwCw2kILPKcGuDatDqtw5TFOgKzAsKhxfbbYg0yAwQvruTpw5rFLme+XWiqPYqT5JzHDq9iuQadzlhCl6HjeNatFjbezeKEUl3//14OARR6/1SLLIM6ksmgUi62EDof0ai+lzwzVW6q8ghpkbxjRFLYxD+QVn3hBSBJNWGqJvb0L+G8BbTI1awLOB7308i6Pd+mExAtYaAsXLXqm/VwDl3CLOXwVHHvIQaTEySamc3YYpk4w25OMsWJNsNGM5eRDS/lB0hVlJtH2/ynZ69kDWmuzKpQUoaJ8EuoHJKXy8OKr76lS5RuBsPIuODeX0+KO/r8KVEusDjV0mVdYV/ktIdr16FDlNTapSA+B1W5WPd3PmH0jbbK+zjew3wkI/VazxZm/uk3JVucXP9e7GRQKARIJg,iv:qmUL0NcjJjLlIPpw6ozAWmIiSV2f+bS81Xs8OYGgLfU=,tag:QQb0UI4e+ZRX1dOnlsxVfA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjZnYXVCeDNRd2xTTUZB
            STVlS3pNMTltZmREV0J6NTJ1QTJrcVpDaFUwCmV5aUlSZFBsNXZBdk15R0dUVnpv
            WVZIUUM2VVhEZ1JOV1JqVEhxdDhVWEUKLS0tIHdmVllRNmpZZ1o5cEdnbncyNno0
            VkNkUHpyYmxaNVZUcS84T3BPNHo1MEEKQ68RnrwhFZAEHPu3nCDJk1dnF63hON1I
            z1l+BHk1xdFwRA0qw0h0cWOPc2UVDZC+XeTZMWIMO3LhWyYwU0pK3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T10:56:14Z"
    mac: ENC[AES256_GCM,data:WM5AfBC1qXa//T4baAQxm7VFHZtlP36LUxs/eKM9qnIITJwKqmklngWtqF9lziRQwjDoGiuR1iHpJKcLdb5FnA12uZtFfXGQ8dxBxRkfIxQ75ASjF8r5LK5dhkbkGAbNcfJE0+I8PmTWstV0hFSclVtZn7hDwIBIs7Osf85DjbM=,iv:OjrjoX6l7pTq9czkNjoDjI+z49779TCxXn/1sMODMEk=,tag:SAGapNVbhqxo4npz0fn3Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
