apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:q8/QpuIJsMO4C2Z6ihAh486GcMe913T3eDslXpauG44=,iv:leY15PbvfUYqBNMdi4/h6i1N3CKIPSutit4QVumiLDc=,tag:WOZM0npN/ZWtZ0qZd67jWg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTHIwLzFsM1U2N2NtSWVN
        bC9YNTJ3eklHeVF5MGVsV2xqK1pYZHdMcVdVCnhKVDhCcWJTVG5IU1JpQmlRSWxY
        cmlhWFlTd2FVeVRJMUQzTTVYTXFTU0UKLS0tIGUyNCs2K0lPbXA4SUYvS3NwMnJO
        SWowYzQwaWtrM3ZseGdXK2hFbXJDRUkKf33avliUBEVJEG75pCYX4Zp0RW3ecxwF
        EddsepaxjSSsK6rsW+sh1S452b4yp7kChSBLheOHtyldS5cFCh7LLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T20:38:29Z"
  mac: ENC[AES256_GCM,data:TRI9T7djvEQXmRpRR83kxsCNDLu97HglD3UDJigTCoogTFlh/IdADEBmG2jzQ5zGpEEqv3hLZpTjO7wrZ6MhPqdBKUwtv4oPiCyZNbD/2jAZZNpjlqX65M5XXmhZYE+UjVWq2+ZFDfTExpBNkA5//9ebXZE+qQ+zfvv4rc0cYNI=,iv:LccTvoIQSDL1XBMF8DjrkdWbNfsLdm9+8BRqvDxRIUY=,tag:R6VlyY7hXRd0nKRvbm/QKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
