apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:Q0oq2fZnD87OYWvsfYQ2ZdT/hVCj2wdFXQaqE+3J6KMSCVeniuos8Q==,iv:pBZH8aU6clpE1doSqBdIo5cKx5ApBnY7jOnzXKTbHMs=,tag:oof5IvwoVWzcMQI+fjZF2Q==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:vkqUEHMkymfRkAZhrGDWYuhdRp0GTBt+fjfDStUYZwzmAmW7TMy88wStVcoTFv9Trb/dYV7hEivOT0U/a8R1R1ScM/uGy+lAfqzz5h1OgQhUCKtUesGZzPbn7gp5adB7MFPkZWtB2bR89/inwi5jJmPSPbWwIdBNgcRJuTdpWSU=,iv:12TRwQDFBIOQOdH9JGoylF4+HzKs5/eN0jKC8ZWQq88=,tag:ZfIIC2VPjDjnIb/nhibNgA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dENQSVh2NU9yMXc1WEJR
            djNUeW50YkZKdU1pSWNDbDBmWnQyMnZROURFCkVzQmZjakd3TEwzY09mYjdlSUd5
            VksrdTBJZWNUZlJSMzRPdVBCdUlGRVEKLS0tIEtpeis5MXJjbU5SaVVmd0N0YW41
            UGtaUXNRRExKMmJoVHpQS3FuY2VGemcKGqmjtXXlQ20E0UfbZ+jMhnDW6q0KDGix
            /JQMKHl4S2m3HW3U9cusJzTBVk7soC6BXQAr/xPAzAReq4HYo5bH4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T18:01:27Z"
    mac: ENC[AES256_GCM,data:q2toHUdefLbiemccePdAkjfbTyZXDkZ2qBwbHffe6DfKbWI0FnL1MZnjVSAhc5T/qX2+u92Q6IIqj0bYxJaYOuDqxrlR70OwtygO809jaDubt3VrY3M6b3pIN8cnyq8Sski92VvJQnUY43KgpnLUl0RzeDNzmSdqsfCS3cibAFQ=,iv:rqjCKykMVNtPT1YcaFh+vWI6AKeZpoQh0qhwow2IqK4=,tag:zxf6BTg/xhA6/NLxPC7j5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
