apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Rig6C83HF/AqrI7bELAMhj5RZSiBPl/LDoIpJ2PgIBg9+pWbXNN1BQ==,iv:Ylo+bmwcui4QlycI0wntlykfnWVPthNZNTtqJ+Q6zjs=,tag:eZM3zOeoyvmyKCrOwlhd6w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:4Acx22geNVzk9BAcOKYbVRzCB97aRw2hKQWgu4Vl90eSOOExjlPyIAuV+DpjFcRUXWFz558rfQrTVmZ+u4XBDO4C7A9QdJydhngdMwnn7Mzcwtsc6Qr9/dr4LCXag9ZgtJPHGq9gKciMIwcIvFFd2psXIg+mOKqTyC7ZtrR3kuo=,iv:cI64AL7+sNePRa/aXqRS70dCkoj0f6yK8L9hxM/84MM=,tag:JcQB/sJUan62UZ+TfQ4rdg==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:EeFLQDbRgDHMVJQCjGuXf6ruFRLp5kQ9F1eS33yxv4mG4xN0o2teJth0rC78pRCEpZRFW7Llwg==,iv:IK1IcxXdgWjmj5CACIccJl6rWSECPoN1tmMHcikSPkM=,tag:Y1SVaPlRw5Bpx3NcdLBWLw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:FwCFqhJ/LUj6fGM5rp8MQfH/MMg=,iv:IFN7NVtXmmFVCd2bJVccLFKTk5yfnFBTEaafBiS/SOM=,tag:F49XWLFgxBQMN+C1ps5Riw==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbGpkTW5YbkhYaGFJbFRZ
            K1doSktSb2lGK29QMVE4MDZ5ZUtZUU1aTVFzCnlMYzdNRnBMRjI4VkdVUGFKQ0tx
            ZUttbi9LRkhUcXV0a2NQN01NcnhWUlkKLS0tIHFUSkxzd0NpTmFoM09rQ0pXUzNk
            NmlwM1Z6ZW1iN3NrbHF3RWFZTHBmLzgKRwOtbPSPyG6KGCS4Di2n3h7u2Vt8jKe7
            Rr472LPmA+qoiZSbcq6oi4QE1KlanpltvTIke5TKQlz4rt132DIlog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T18:14:15Z"
    mac: ENC[AES256_GCM,data:73i3J5q2kcw26HR188sRA9mjYgH3EiwTd1Y/W7qFUqY6CxzAkQg40JrR3ofv/aM8Df5U5Oiy+308XkYubel1S1y5zaaej2z4CKdEYMxeh6uhOpBBHOBDXFk9sWU6nKO6D6u2L7leKW2oRus2qQwisxKOj7bE5AawH2+NMFtClCA=,iv:SvyS2BOCOmVTDTrPBZm+QH6MSSbq5vylCalceY/BXQI=,tag:6bWngkMROj49zCQnMustSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
