apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
type: Opaque
stringData:
  clientID: ENC[AES256_GCM,data:SP7qhNbaAFHH9qJJpdNOHjrV4WJo7Oc4RZavsP87xJNq6F8HLLzTlQ==,iv:4LEsoffID0B8hvi1LgCXOHcxYKQsDKNTWjxU1M+Itc0=,tag:XPrudXcEy2ooH/vadCdOIg==,type:str]
  clientSecret: ENC[AES256_GCM,data:r+fHS4YqeqTD27yKooDQpB7qL5Ft4CwMTQvVURJZ2GCklCDYExQelx+jt3rOI74mxEP+MlD0FR9b+uAzk+O46Y/sOc1vT+ldfiFwhv+2wEx3B7TgZHjv7AHKI970wnvNGQV2VuJ5YIDcajGUQOdBw+iEFI6B9uGEp4wHAOEiySU=,iv:uTiELPPW535ye3TTH+LANWsycxm3QC6BFD2rySyoUW0=,tag:XvUWNG3CATW6azyFrVdtqA==,type:str]
  issuerURL: ENC[AES256_GCM,data:k74cmUz4Xs7CHd5bmgLauBM4PjwOk2/0drRMeQBM6N44N7I87DOy4IJTS7NUxxP77QBfb/miBg==,iv:06DnuLKRXZYI4YyZ45dZydO9IYeXKHZMkkHV+up70mo=,tag:wkdzfkCVL2ixL5oX+1uK8w==,type:str]
  scopes: ENC[AES256_GCM,data:Bz07FlLzxMEj+cWXzLXfSl5aVc0=,iv:LoVWYqq81WNeGSYHOf3CAY4kF0xjFuIDbYF6ck14ZCA=,tag:tsFujNX0r8nJ1gaSY4mcGA==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbGpkTW5YbkhYaGFJbFRZ
        K1doSktSb2lGK29QMVE4MDZ5ZUtZUU1aTVFzCnlMYzdNRnBMRjI4VkdVUGFKQ0tx
        ZUttbi9LRkhUcXV0a2NQN01NcnhWUlkKLS0tIHFUSkxzd0NpTmFoM09rQ0pXUzNk
        NmlwM1Z6ZW1iN3NrbHF3RWFZTHBmLzgKRwOtbPSPyG6KGCS4Di2n3h7u2Vt8jKe7
        Rr472LPmA+qoiZSbcq6oi4QE1KlanpltvTIke5TKQlz4rt132DIlog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T17:53:07Z"
  mac: ENC[AES256_GCM,data:ceNQn3JwsA/zmnQbqiJyB3qZBdx3XV4tIM3Movrpo5fHZSmltXCjREYMH29Nd8vmcG9a7cIFd5PZyIgTdqzfQc+SwbG3UI7sfUAaApL8aoqdstO6xrdcO3vG3XDRkztrHGAnlHYl/siMZt5Nn/mHhHgLg1l5ujJlclbEkepX/5s=,iv:0uLt1Bwa875Za1pghQjAgfMGV+4PCano04GizGJNBig=,tag:kr2W7pxZQ22IZmQzrBfolw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
