apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:K7pDOBtqq8aEazVr1DgqY9CPVY85nz57BoJyoTISHUM=,iv:zrDHSDDOknTHRM+0qWCoiJN8m6KWuAjxXaXj20XjbWc=,tag:koz1OkvrPQos1PFO/rHV/A==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUnhQRlM1Y1dwZUpsRVhO
        ZzBpZU5SVGczYmZuV0tLNm1Jd2JMd1Q5a2dFCmtrY2wxTlJRWU9SQlBVN0w2Mk5E
        cGxUMVFXU3V2YUFSaWlEdm01VVNtVFEKLS0tIGxqSkpYWnpXNjRENytMTmlwaUdV
        ZE5UamdIc3BicjhpUmlOOHlKWGZaLzgKC8uy+M7Ni9FuzYsL58xjc2+WCWyQG+bk
        lh0QtKNUjL9xeqWjvW6n27B/3//Ospj4PWFK++/A0IDv/xsRYXDn+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T06:37:28Z"
  mac: ENC[AES256_GCM,data:KsjB40ywG8zifci94x+myQk+GSWedlbavmXuM/qbrANbZJhetDFzr5oW2SjN/KAgYiDMQ7RcuU8bCgFHcgOuRnSnaO7Q+UyGvAKTvcYefRK2tz2YXVHFzAwUA5xyAupf5j/mCFR8xC1gxpiwaY/Jc630G84TIYWAH6Jn5B1Z8Ag=,iv:gO4Sp7BGYsLcpsDaUtRyt5rqJ2eUDoVcfQfSGtfy0vs=,tag:mQs7JaVMdAfyz6Emsx7Jng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
