apiVersion: v1
kind: Secret
metadata:
    name: rsshub-secret
stringData:
    PIXIV_REFRESHTOKEN: ENC[AES256_GCM,data:53ZeqjNtArU7KSC2u06lFn+a+0fNeJjbB/DNOj/Pk6ZCTBHicJxshEelCQ==,iv:4fxkEsyR+Nky5tHUc9xLh1C2E2nqYZM+fifB3vlQrmQ=,tag:Pr9+1aS7DlePTTiRdfk0lw==,type:str]
    FANTIA_COOKIE: ENC[AES256_GCM,data:CCedL4O8M0chcipP5whPHSskkaDj6TU02WqnL924yBxMLt8crQrbqoEE+6vApF7LzYQTA6TG9QBTnZcV+NeYFTSXI0YJCosiUK29GMQsHoCIJsKXOwRMjIMa9KklUGQ/cdn0yQK4G3EQ3yllvD8eaafZggfvec3UqLL1HbfGQsnivWYdkYogfCUmBCDVX+UnmWT15HW8haFKEqAEylhj10ttI9nA+t9Tbcup4ZNhupHjcqlr5/L3qJCupP8jRHjSrwlnBNeetoP8OSp5WzZrEXS9TrKTm9xov2CBBck+bCvKP0BKvyjPGlsysVb0aeZq4l7Yjxe4,iv:dfZUI2wjpbxtwLDIHwzZxhxz1incHNqa8r2guGeREME=,tag:hGH8AVF+f2crbnayZLrraw==,type:str]
    EH_IPB_MEMBER_ID: ENC[AES256_GCM,data:c4oQj+mW,iv:9d74VYkISAAySh+/QUTV60a4GCYGeXCGwTZekakBdpI=,tag:EKrVexErKWv2Oy17i2EJJQ==,type:str]
    EH_IPB_PASS_HASH: ENC[AES256_GCM,data:Ko4KtXBXYmECJsH1KKMfCx4nx9KsPmufoT/ZVCPF1/c=,iv:YcwMjVnMiGmvAk2ct4GWK1I22RpYfJMWZAgAricFh+4=,tag:CXbQwEk1pPuGJ1AxWNerfQ==,type:str]
    EH_SK: ENC[AES256_GCM,data:SImUf1PWZkFGp51wIv3vLtf/kdrPlNBEPlzwdQ==,iv:+jONekvfh6n3RgZb3JoMbaUZG+9A5yqx6WmpyTiPYW0=,tag:x6t3UzgiSlGaSNGO9tyJ6g==,type:str]
    EH_IGNEOUS: ENC[AES256_GCM,data:ZsCRHTCxRIP8ct66mkytFkI=,iv:trabd2NOEq4Es3mi1Dzw1rvYcuwj/uLkGu/sT60GW2o=,tag:n4m3QXmFEtyzHPAyKYE+WQ==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3RXeUo2czZCZGZPaDlN
            cUxiUFFHZkEybDJ0alpmWXVVbm5HdENOb0dNCkkzNzRhQUF1K1AxYUZZOWFsUyt0
            cXA5RzhwclNOT1p3N2RtamExcmRtWGMKLS0tIHVUSytDWHNtaG1kQ0hDUkhYcWZu
            YmVqZFc0cVpSNWIreXM3NHM2cGRmOTAKifsTWFeGeasD2hKGoT4Kd3aMF/ogwtPq
            6M+3TE/sTvNVBwHR+4aGjzxHIV0VymbWV7iCAfDuikwC1GU9YEMBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T14:18:42Z"
    mac: ENC[AES256_GCM,data:NFFI7bFNE1HPU/TWf+0+4KIb2BsZ40H8XF6lRBLsBpdwpAn8GqOT1h4eJkfpyIlQrtvBgN4FBbL5h+EPDHf+I6umzpWCamK3bwKmLnI5QIXn7QdjnrEN/hmiKOBQfi1CfutOmc4A9ksYRO7+euAbL2qGYFIKWa01RUHRJpHVLR8=,iv:gz1JEfl88hJGH8D7xI6t9B5X8P4re6ZlDR9xzdd3TJE=,tag:d9nXLDsaWYW4V6KBGJL/0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
