apiVersion: v1
kind: Secret
metadata:
    name: rsshub-secret
stringData:
    PIXIV_REFRESHTOKEN: ENC[AES256_GCM,data:53ZeqjNtArU7KSC2u06lFn+a+0fNeJjbB/DNOj/Pk6ZCTBHicJxshEelCQ==,iv:4fxkEsyR+Nky5tHUc9xLh1C2E2nqYZM+fifB3vlQrmQ=,tag:Pr9+1aS7DlePTTiRdfk0lw==,type:str]
    FANTIA_COOKIE: ENC[AES256_GCM,data:CCedL4O8M0chcipP5whPHSskkaDj6TU02WqnL924yBxMLt8crQrbqoEE+6vApF7LzYQTA6TG9QBTnZcV+NeYFTSXI0YJCosiUK29GMQsHoCIJsKXOwRMjIMa9KklUGQ/cdn0yQK4G3EQ3yllvD8eaafZggfvec3UqLL1HbfGQsnivWYdkYogfCUmBCDVX+UnmWT15HW8haFKEqAEylhj10ttI9nA+t9Tbcup4ZNhupHjcqlr5/L3qJCupP8jRHjSrwlnBNeetoP8OSp5WzZrEXS9TrKTm9xov2CBBck+bCvKP0BKvyjPGlsysVb0aeZq4l7Yjxe4,iv:dfZUI2wjpbxtwLDIHwzZxhxz1incHNqa8r2guGeREME=,tag:hGH8AVF+f2crbnayZLrraw==,type:str]
    EH_IPB_MEMBER_ID: ENC[AES256_GCM,data:c4oQj+mW,iv:9d74VYkISAAySh+/QUTV60a4GCYGeXCGwTZekakBdpI=,tag:EKrVexErKWv2Oy17i2EJJQ==,type:str]
    EH_IPB_PASS_HASH: ENC[AES256_GCM,data:Ko4KtXBXYmECJsH1KKMfCx4nx9KsPmufoT/ZVCPF1/c=,iv:YcwMjVnMiGmvAk2ct4GWK1I22RpYfJMWZAgAricFh+4=,tag:CXbQwEk1pPuGJ1AxWNerfQ==,type:str]
    EH_SK: ENC[AES256_GCM,data:SImUf1PWZkFGp51wIv3vLtf/kdrPlNBEPlzwdQ==,iv:+jONekvfh6n3RgZb3JoMbaUZG+9A5yqx6WmpyTiPYW0=,tag:x6t3UzgiSlGaSNGO9tyJ6g==,type:str]
    EH_IGNEOUS: ENC[AES256_GCM,data:IWk4MJa98L1TzmViNZqX37c=,iv:ZUv6Su7deSz5fbhn0VM2u3Zm9xPKG52kNLuadLKwOgg=,tag:boHFgp1VDdJkvNKlQIdodg==,type:str]
    TWITTER_CONSUMER_KEY: ENC[AES256_GCM,data:IBEIGjK8XavhmYbRDKHIWFPPnsvJpdY9vQ==,iv:Trr7hoHaz3YM6AvL6ZDgqokMvGGPv9uY47jYEqyeJy4=,tag:6uHvkQRmLAtPCIOcten/fw==,type:str]
    TWITTER_CONSUMER_SECRET: ENC[AES256_GCM,data:ay5c2vFNxm0BNGoEqRE/R5SXQERjx4GdG5nx20QnL2+0aaDXIl43wzZnq6aKXyf4PKE=,iv:jcKQbaeWuwlY1fDCTK7kLzEAYV9RVw/B3koXr3v/Grk=,tag:iZKi38AoA1AjJQmebAF1PQ==,type:str]
    TWITTER_ACCESS_TOKEN: ENC[AES256_GCM,data:lHEdnOllphHDaZgwuYydhupgg3H4CSlUizGrG7gNsG/9y+zqqZKGOpz/zkrd0tXshb4=,iv:oKgzJgkjTMkcOkL2Wf+rgsIZZ+a/r7kpZYelLJ44ESk=,tag:dYm58YZHq+WEa/4n8z8ykw==,type:str]
    TWITTER_ACCESS_SECRET: ENC[AES256_GCM,data:bS4fXXrKmVHd6fFVnkqJsHeff4jvuMzQPlZ0ExaQDGFwXEDg/Lra+azlAKA3,iv:/pAXt0eqDx3oCJIq66qx1Zy/xYlq7ST0mc68NSeEcoA=,tag:eD6xjsqDbFX3vVgsmGp9KQ==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3RXeUo2czZCZGZPaDlN
            cUxiUFFHZkEybDJ0alpmWXVVbm5HdENOb0dNCkkzNzRhQUF1K1AxYUZZOWFsUyt0
            cXA5RzhwclNOT1p3N2RtamExcmRtWGMKLS0tIHVUSytDWHNtaG1kQ0hDUkhYcWZu
            YmVqZFc0cVpSNWIreXM3NHM2cGRmOTAKifsTWFeGeasD2hKGoT4Kd3aMF/ogwtPq
            6M+3TE/sTvNVBwHR+4aGjzxHIV0VymbWV7iCAfDuikwC1GU9YEMBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T19:37:25Z"
    mac: ENC[AES256_GCM,data:mrYRT4pcizVpsGMBg9K7yHZWygxSvzrvV+i7W65Z+B+U/Vg9A9bskCXBNOgeSHx7pjGybvZy8vzyqj+95CNCMgBtiZCKpoZBKYoGF74/FJrBu6QhwoOKxgBn8hskH7SWaqG6j9IA2RjQDZeG7cG5L2XnT1mjFpiU/slWNkxHspo=,iv:xAb88aA+FG9S2bnFg95VEMRwzf6Rc5DNcQsLb0EU9g8=,tag:d9igzBA1AF+niz0H56l1Ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
