apiVersion: v1
kind: Secret
metadata:
    name: rsshub-secret
stringData:
    PIXIV_REFRESHTOKEN: ENC[AES256_GCM,data:53ZeqjNtArU7KSC2u06lFn+a+0fNeJjbB/DNOj/Pk6ZCTBHicJxshEelCQ==,iv:4fxkEsyR+Nky5tHUc9xLh1C2E2nqYZM+fifB3vlQrmQ=,tag:Pr9+1aS7DlePTTiRdfk0lw==,type:str]
    FANTIA_COOKIE: ENC[AES256_GCM,data:CCedL4O8M0chcipP5whPHSskkaDj6TU02WqnL924yBxMLt8crQrbqoEE+6vApF7LzYQTA6TG9QBTnZcV+NeYFTSXI0YJCosiUK29GMQsHoCIJsKXOwRMjIMa9KklUGQ/cdn0yQK4G3EQ3yllvD8eaafZggfvec3UqLL1HbfGQsnivWYdkYogfCUmBCDVX+UnmWT15HW8haFKEqAEylhj10ttI9nA+t9Tbcup4ZNhupHjcqlr5/L3qJCupP8jRHjSrwlnBNeetoP8OSp5WzZrEXS9TrKTm9xov2CBBck+bCvKP0BKvyjPGlsysVb0aeZq4l7Yjxe4,iv:dfZUI2wjpbxtwLDIHwzZxhxz1incHNqa8r2guGeREME=,tag:hGH8AVF+f2crbnayZLrraw==,type:str]
    EH_IPB_MEMBER_ID: ENC[AES256_GCM,data:c4oQj+mW,iv:9d74VYkISAAySh+/QUTV60a4GCYGeXCGwTZekakBdpI=,tag:EKrVexErKWv2Oy17i2EJJQ==,type:str]
    EH_IPB_PASS_HASH: ENC[AES256_GCM,data:Ko4KtXBXYmECJsH1KKMfCx4nx9KsPmufoT/ZVCPF1/c=,iv:YcwMjVnMiGmvAk2ct4GWK1I22RpYfJMWZAgAricFh+4=,tag:CXbQwEk1pPuGJ1AxWNerfQ==,type:str]
    EH_SK: ENC[AES256_GCM,data:SImUf1PWZkFGp51wIv3vLtf/kdrPlNBEPlzwdQ==,iv:+jONekvfh6n3RgZb3JoMbaUZG+9A5yqx6WmpyTiPYW0=,tag:x6t3UzgiSlGaSNGO9tyJ6g==,type:str]
    EH_IGNEOUS: ENC[AES256_GCM,data:IWk4MJa98L1TzmViNZqX37c=,iv:ZUv6Su7deSz5fbhn0VM2u3Zm9xPKG52kNLuadLKwOgg=,tag:boHFgp1VDdJkvNKlQIdodg==,type:str]
    TWITTER_CONSUMER_KEY: ENC[AES256_GCM,data:ZXA+fTvQGsbldT6NX6An4CNdOz92gWI/yA==,iv:duYU6Wla2foQtnd2r6iYVHrvTbAdxPMBqMAtEHDNOD8=,tag:jXMjPRZqCABCxanLXID8og==,type:str]
    TWITTER_CONSUMER_SECRET: ENC[AES256_GCM,data:SDZKCnC8u3p0wXP8AqKl13jxqC4CIA42HLx38iIHsWypkSuRL5aySmHqyb7COf+xSYM=,iv:ek7JiiGJZTvPJzeW46oRokYqTr1HP/6JdL9wCkrFYpU=,tag:94b3fsurMhQB923l+ddqBA==,type:str]
    TWITTER_ACCESS_TOKEN: ENC[AES256_GCM,data:cBXVtcibBas8vi/ffDhj5RCgxSNIOg1AxFYn4+u+ygpXaRfpVYxtHO57JfKGmaY/uiY=,iv:4T9oLEBxGHmIuNKfSv0/Cddzxtibc7QUGnMPTGgJ+w0=,tag:we+qVlIda6ze+kmqEkltMw==,type:str]
    TWITTER_ACCESS_SECRET: ENC[AES256_GCM,data:Y/t9vaoZsY9pWmDXdiP+rigvUp8rnWXvs3DkpsK8nTrViiF4pmpbcV/xgbe+,iv:eTc6+vuztgPLqIXG5wnG3xaKtuhJ+Go7qE5i28mckUM=,tag:bySVQnYWwyOIkrZ6bh41KQ==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3RXeUo2czZCZGZPaDlN
            cUxiUFFHZkEybDJ0alpmWXVVbm5HdENOb0dNCkkzNzRhQUF1K1AxYUZZOWFsUyt0
            cXA5RzhwclNOT1p3N2RtamExcmRtWGMKLS0tIHVUSytDWHNtaG1kQ0hDUkhYcWZu
            YmVqZFc0cVpSNWIreXM3NHM2cGRmOTAKifsTWFeGeasD2hKGoT4Kd3aMF/ogwtPq
            6M+3TE/sTvNVBwHR+4aGjzxHIV0VymbWV7iCAfDuikwC1GU9YEMBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T19:33:26Z"
    mac: ENC[AES256_GCM,data:fEE45/EIQ02Ynf58IlwbBsVwG5Y/v2CuVBy0v+8gb6B129wGjVsD8nBKngg8M+hzZ2GNYbN60c4C6vMcnUQj57rTqHzjHNK0HvgOWtpNyx08MSIvBAYj5YgGmtlaDruh+BPc+TxikmqYfXaDspZVs+abjFnF+vI06XYN0llxn8g=,iv:Kb00Fb3OvRv0cnWu+tBbfJ5ecSTQwRPGeUrOcnUa61w=,tag:x56bmfUd8q6VK7cIsyVyYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
