apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
type: Opaque
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:QVWYkjmbU1Qp53c+kL5KY9KqBt/HE2X6VPc2ZBzRgG6thPzg9k+XFOPFXA==,iv:+kxYf3w2qTjhExy+zJlbcVV2Rcam4xMnoAn3TncDn7M=,tag:SLaYp2/I3QTzL6Act39djQ==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQlNCbzZEOVFSUExHSFJE
        Tis4RHM5UjF6b3J1NkZVU3EyaTlNVkxlT3lNCkJrYVhmRnNjYTlnc09PMGhkL01v
        bVNlZEErZmJiM3N0SW1aUWlYeU1BRkUKLS0tIGRzNTJFb2t3T3Q3M3RXMGpkRENI
        aGNFRVgzdHVVRWlRRlJYa3U5ejk2WVkKEsnN3RqOs44rxw724F4ZBZ6xBB8NlTM5
        CzJ7qDkeyCQ21Dqj6wWwk6wj+uFDFsqbpinvt7+tdqtT3Ely57v99w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T19:38:25Z"
  mac: ENC[AES256_GCM,data:n8uTSQVqkPW27yeaws0BjsSLcRTuGBlFuXs1i+43MSACPpy/AMd9lSS8aLQmAOveVXjqj3iKry9nL1/W5/tWb3quW/nKSAFFsCoOnDodfuei/VevpmRt4AW2TDeMPDxSWU5rrc3KMSozBozIDdnkb5RJgpO+/eNGoN4ULtUN2to=,iv:rJ+K52IXA7AoHTaRxNATnnoblmKC289ynhCJErsyi94=,tag:0xz6/m14HzMAY1op+ZAEQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
