---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-synapse
spec:
  parentRefs:
    - { name: external, namespace: kube-system }
    - { name: internal, namespace: kube-system }
  hostnames:
    - "matrix.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - name: matrix-synapse
          namespace: matrix
          port: 8008
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: matrix-well-known
          namespace: matrix
          port: 8010
      matches:
        - path:
            type: PathPrefix
            value: /.well-known/

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-auth-service
spec:
  parentRefs:
    - { name: external, namespace: kube-system }
    - { name: internal, namespace: kube-system }
  hostnames:
    - "matrix-auth.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - name: matrix-matrix-authentication-service
          namespace: matrix
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-admin
spec:
  parentRefs:
    - { name: internal, namespace: kube-system }
  hostnames:
    - "matrix-admin.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - name: matrix-element-admin
          namespace: matrix
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
