apiVersion: v1
kind: Secret
metadata:
    name: matrix-secret
stringData:
    CLIENT_SECRET: ENC[AES256_GCM,data:Eq7re9nEy9z3c/SCa1hcBWk7gwIBbe4qFH7cK4PW0MiGZlhnKIclKq/1+qFOTQBPvgX1jpwjcIkNi/7Uduk9trCiG6HV1Zi9tPB20OLgXZgrcDFVwVGEfkN1Awkzj8U01XvdbepR3Ddw59i64zTR6JQ2riCJwD+TpLcx6qnGLnI=,iv:A7z95tHrBB1IXeaOX7LC4TUIIGb3fza7HTsrg7/1pVo=,tag:TarIPLhan38f67eMv/4Zhw==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3RXeUo2czZCZGZPaDlN
            cUxiUFFHZkEybDJ0alpmWXVVbm5HdENOb0dNCkkzNzRhQUF1K1AxYUZZOWFsUyt0
            cXA5RzhwclNOT1p3N2RtamExcmRtWGMKLS0tIHVUSytDWHNtaG1kQ0hDUkhYcWZu
            YmVqZFc0cVpSNWIreXM3NHM2cGRmOTAKifsTWFeGeasD2hKGoT4Kd3aMF/ogwtPq
            6M+3TE/sTvNVBwHR+4aGjzxHIV0VymbWV7iCAfDuikwC1GU9YEMBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T18:38:23Z"
    mac: ENC[AES256_GCM,data:5wXDNPvqoOg4V9cnjcsOGysTpVzydwkAgYTJbxPP6m0cn4oIX2QayBzXwDEJKFIB1g7g6g0snrcLSumTGLuw5IBwoTKhnvblyZ8hL7ihhJbXGjgzcDGgnnTmwtjwS3o23cfNv7uUu2K9jtX70ENe9dfLT0ALs9Mh4yOALIIDr6E=,iv:rHrgE6Wxb7aj0LbPMVSgabVEr+4jHSCjAVZV+YYxYQ0=,tag:Fs85Ez/jn5EUssKP2nK4ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
