apiVersion: v1
kind: Secret
metadata:
    name: danbooru-secret
stringData:
    DANBOORU_SECRET_KEY_BASE: ENC[AES256_GCM,data:Fw2OCHhvGFeFtZVulX3NBQOBIPf+h4wqMVNiRQiovZ9QoXcxe+7cPVsxHaY=,iv:KUUUwQZi5WPJ3IU5A9qidFrGdRjX2QmsloZC9ZpEJwE=,tag:20+ZQY+PhwmcQAnh8DO5Ig==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlI1V1Vra29tZXpoVDZq
            Q3g5Ty9aWGJtM2FmYk9KY0dlQ0tZbHRvN1V3CkxuVTVVWEVzU21LTDRUR29iUXpN
            TG1YVjVXM3hZMzFFM0xicDFJM1dLVlEKLS0tIFE1TzlTSUlDZ1pibkVuK0FzQnAz
            YmoyTU1RY1p4RmE4K1VBSURyblhEbXcKTvvIQW+sGq3PsR9mtw6EtHBmCqmm9R8/
            G7YVLcOiNfsZTj87VE9xtrnzL5iRx1XN6zqoCTEbSgK67jul4HmASA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T17:03:19Z"
    mac: ENC[AES256_GCM,data:K1czR9o9GgIjw59BfOwYb2HEBDZ6TQ4fthgIlJEEJ5Z4zEe5QvjtzQu/tNSOP4U8ohHfmeVk/xvCYRAfL+FqKhb/cyj+28RbUHWkGBdM7ILroSpOubqQKzRpz3k8gGHi444cIXM5iQ0w2XwzhsF8VnZs/abUvXMr/Rxq7IzNA1w=,iv:4D8bSWT8Kpq5jTjQecoqBDnEJxaS94dChzPpIw92++M=,tag:m5+7ak4NmYx2goiPGBu1xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.0
