apiVersion: v1
kind: Secret
metadata:
    name: danbooru-secret
stringData:
    DANBOORU_SECRET_KEY_BASE: ENC[AES256_GCM,data:Fw2OCHhvGFeFtZVulX3NBQOBIPf+h4wqMVNiRQiovZ9QoXcxe+7cPVsxHaY=,iv:KUUUwQZi5WPJ3IU5A9qidFrGdRjX2QmsloZC9ZpEJwE=,tag:20+ZQY+PhwmcQAnh8DO5Ig==,type:str]
    DANBOORU_TWITTER_AUTH_TOKEN: ENC[AES256_GCM,data:kvqZnAaJnHnK4IdIBP5px5JsTxY5jbRSMmio+rmh67BqIKd4bkxysQ==,iv:ztVHOR9niwUGFFGadzLs7lDVjBsXW0TAEcCpwKCNC5Y=,tag:UTznWqb6wwzZDM6CQRyYjA==,type:str]
    DANBOORU_TWITTER_CSRF_TOKEN: ENC[AES256_GCM,data:Bqj6WAHSukApU4lVUEY/irir7h4yQi15GOqmkzcStBpFk+dyNHs6T/NvBcZEdUwC67UbxKMqIHt7nYLEQwUNw2Pzku5ZRVFuMGh3CbbBea/StMm8Tn+A8swNtSt7A37DnVd+n3bjneTFjOzbprqS+MrksFghpxfTrd2SYwi7H17uVJ+3AldZn9gAKEjW4BURxZf84elxkw8OnA/x/QyVbA==,iv:hMX0r1b8suYCEvWxXbxT3x41hOiFRfOFFbfTyD8ZkrM=,tag:RmgM4qZArsyUIdKG2NyrUg==,type:str]
    DANBOORU_PIXIV_PHPSESSID: ENC[AES256_GCM,data:nlgEeihA4ixS9JUtdh3bS+Qqy4L1Q4SO48XAg9mWs2SyoMeh6o5egw==,iv:RnposLwlEz4YZF4pRMb7jxrs9+51esA0HZnTELnU8Ng=,tag:rTMu/zB2PD3IIo2qV7FnFw==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlI1V1Vra29tZXpoVDZq
            Q3g5Ty9aWGJtM2FmYk9KY0dlQ0tZbHRvN1V3CkxuVTVVWEVzU21LTDRUR29iUXpN
            TG1YVjVXM3hZMzFFM0xicDFJM1dLVlEKLS0tIFE1TzlTSUlDZ1pibkVuK0FzQnAz
            YmoyTU1RY1p4RmE4K1VBSURyblhEbXcKTvvIQW+sGq3PsR9mtw6EtHBmCqmm9R8/
            G7YVLcOiNfsZTj87VE9xtrnzL5iRx1XN6zqoCTEbSgK67jul4HmASA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:12:33Z"
    mac: ENC[AES256_GCM,data:WZMP7ss5yF3G2GvM1MXbrDjwbIqAPJF+aQk6nD1kismELJcl31qv0Qq8m5acspUVPUyaz5f0zH7XsEFMviFh7VKlQCUXxRnnGvVhcYd8Sg6lb6twDAAlSKB6CW5sJSVv7SYLpwsnS1T2mF2jcTqgaKAcgVrktYc37GcWaqvsQ3s=,iv:Of7Fim/Ca4t0ESQPMukWHnH4NmmqYNkcgjaM0R1aZNc=,tag:XLgAkAYKPm6fmAmuVsbaNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.0
