apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:t+mrD7x4H0vdSAvZPMDxCJbqA/M=,iv:+hlQo/l1Su4oq5tYFLrzNqwau4kJ5hyvv+ejQsbJIGs=,tag:PLRDdqawsLL5LqWIy493MQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BzQ9vZunaUIghHJ93jis+25Tawee6BaHoPyF154MyVoKLqI1JonaFA==,iv:+2szegZEMr24Swjm1K9ElQ91MFgL7gtTGpFl0jQZ0pc=,tag:ZC/Wv1qCkQLeDKcdgjqNhg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMDR6VTE4S0VmNTdqNzNG
        Qjd4dWdPbnl2N1o1WDVoLzNTaDYySzJ6N2xzCmluSFZteEtIZ3dxMG5SdE1tOFgx
        c2ZucG4zVmkvaUp0ME9TTVpUMGJTOVUKLS0tIEpDTnlRa0Z4WVd6NE1aTUtJSjlI
        VlNQa3QrM0I3RUZ1ZWhQajlnMDBGRlkKcKBlfmBE3U/4N5sL8Ciu1RYaHVzDJTVo
        hQXbHCG/e1Kr/vCyyMCMmX1yD5fwwKKuCLoWqqdSZk+Jo9r5GPazkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T20:27:27Z"
  mac: ENC[AES256_GCM,data:bZYT2dh+qsZNlR9cpMw2Ra1wwPjdXY3GQb1B7Y0alKD+SAhqB+OgyGNAB5394lLgE0KzlJnnSgineA1usCx4Fqh1M2xcn3TR89wXD1MXmHf7QS38FgvEKMfpQ9yH4r5aeD0r7di0nrI+q49xH3doi2rVoS1Xto5uCVRI59rXtto=,iv:I00RlzyZ9K0LjbC+D1t5bbvGFhuf1nRgpkGkxGJd/DI=,tag:AckhvkBXOzqCZureN/ffSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
