---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  CLUSTER_LB_EXT_GATEWAY: '192.168.100.80'
  CLUSTER_LB_INT_GATEWAY: '192.168.100.81'
  CLUSTER_LB_PST_GATEWAY: '192.168.100.82'
  CLUSTER_LB_BTORRENT: '192.168.100.90'
  CLUSTER_LB_SOULSEEK: '192.168.100.100'
  CLUSTER_LB_JELLYFIN: '192.168.100.98'
  CLUSTER_LB_PLEX: '192.168.100.99'
  NAS_ADDRESS: '192.168.1.10'
