apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:lRVIOB4Filf9w4GpSg==,iv:RwTfki9DaWB+KOsBHzftMCwh+tFN+6Ho8ArrwcnvBEg=,tag:mi+Bdv1h+nARj+UeqGjbEw==,type:str]
    CLUSTER_TZ: ENC[AES256_GCM,data:rnx6hmvyAmyhIKfWzg==,iv:CCOtstSF5fDApJFJu1sy5diYwhg2EXnIL87sKeNsMUM=,tag:bcYE5q1NbpJVG9g6/aj5CQ==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:8bZfQqWPV+U3oWr10I/08Q==,iv:H8SXqqfId+ladLQHOoU6HdP8fw7DNQYqpTrkpu6bsig=,tag:YlP5cIu6JUvzWZ1e1X90mA==,type:str]
    MATRIX_CLIENT_SECRET: ENC[AES256_GCM,data:C0sOAX9oqMGP63UIz5dU0xNlzyyMjIctZIUkxLWQwFslMuIAVadsqhLGuvDh82w0LnrpLZe8oECfy5S4wdfKFEfPvVhXOoguH74P4/3JIXl5aJ6YyiGaSPuQU92NSIxV6HabCpBeuCPWCQehfm2PDtiTTf/uhzHoyXEnu2BqZ7U=,iv:fU0Y87p7UR8T0/nEKKVEldHkxB5vZQ2no0WusdKp5xg=,tag:DywceZxb/52ZTrnbgHPNmw==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUHFITlJ4cUp4cVR1dFky
            K2pNTXMzU05MUzFCYy9qb3VlZ0plUTFKMDFNCmhOKzVHUlQzUzhRTHU0cEY3SHZU
            M1JPWG5rU09pN2pOUk4ybEJVYkJsOEUKLS0tIHJlMlhnVGZwTlJzclR0SFFkcEwy
            MldmRUFRTThLeUczLzd6NXczWThQTzgKwPZSh129lzcgYCyZABXXklmbGiA0YFRQ
            3rq0UnlvYeNkt2EZSKr00zyVmdJvyOKYmdyzX1TbbMJsuqMbhZ+QXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T19:22:13Z"
    mac: ENC[AES256_GCM,data:lgYK+ZrZeJp72nbousc/3aris4kCnMcDuUoYb7MyjBNLbHG6aHYy7/1ONSI40d7VYtUX7QDmYUltDbMKt2YQ40nlPsTnDfGw8gXdywawEP0zYORJ7ztqMBUriwXliApKoZS5mRsGEazebT+5441o9Ata3VyutsM9qPRi6NYEajU=,iv:wY40oAJeN0xBL6S4ik5UR3+RKkbONO5PxxbHPuF5mWo=,tag:xlKne4t10b8C3HSOmGrrtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
