apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
stringData:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:lRVIOB4Filf9w4GpSg==,iv:RwTfki9DaWB+KOsBHzftMCwh+tFN+6Ho8ArrwcnvBEg=,tag:mi+Bdv1h+nARj+UeqGjbEw==,type:str]
    CLUSTER_TZ: ENC[AES256_GCM,data:rnx6hmvyAmyhIKfWzg==,iv:CCOtstSF5fDApJFJu1sy5diYwhg2EXnIL87sKeNsMUM=,tag:bcYE5q1NbpJVG9g6/aj5CQ==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:8bZfQqWPV+U3oWr10I/08Q==,iv:H8SXqqfId+ladLQHOoU6HdP8fw7DNQYqpTrkpu6bsig=,tag:YlP5cIu6JUvzWZ1e1X90mA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUHFITlJ4cUp4cVR1dFky
            K2pNTXMzU05MUzFCYy9qb3VlZ0plUTFKMDFNCmhOKzVHUlQzUzhRTHU0cEY3SHZU
            M1JPWG5rU09pN2pOUk4ybEJVYkJsOEUKLS0tIHJlMlhnVGZwTlJzclR0SFFkcEwy
            MldmRUFRTThLeUczLzd6NXczWThQTzgKwPZSh129lzcgYCyZABXXklmbGiA0YFRQ
            3rq0UnlvYeNkt2EZSKr00zyVmdJvyOKYmdyzX1TbbMJsuqMbhZ+QXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T08:14:01Z"
    mac: ENC[AES256_GCM,data:NxtBfLuybAysVd4gCF4ZUsq61BLSmBFmZAs2OE5aUjyS1j/kuH+NdtK2RVRld8Fo/6BRcOxfS4DaQeXtj4gprzogikdbVD6K4tI4je0olFRgfUu85EqhOsCKNVj824WcRN/u9BeUW4xhJst6g+VDtxLlUcYwxL1W04Vl3aFVmqg=,iv:PI+0VmuzX2evGtrFbVJekgOyVyG7guhI52+Yb3NcF6s=,tag:0B1uNfccS8Lh6te32EiSuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
