---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - blackbox-exporter/ks.yaml
  - fluent-bit/ks.yaml
  - gatus/ks.yaml
  - grafana/ks.yaml
  - headlamp/ks.yaml
  - keda/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - silence-operator/ks.yaml
  - victoria-logs/ks.yaml
