apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  slskd.yml: ENC[AES256_GCM,data:LQWKSfZKUZ+zjZrcmVaat/F9kHISKUfmvZu1E6a++H5gDGphjhgpjUj5T6e/5Q1+ueQnnQvHk0s6oOMuKdsoUDnCFtTj6OYKOyqclxtQjvQf1ufBFy4jdkV3eSvxcoBcaZaJCs3mIfrUUazDa4bLbQMmzUQO4y7lsOW8aqQsO12+TUYuzkNye/BIU1N3G2aCd4knuv+GrJnHY9K3DjBjm9151jYIH3iaB2yhpByc0cTOzN7ZSULxgmB8i9iYmoMmuVHcW+Fs/ZCx5ePxJdn4/6DnvPIA89h3TtHn37WnCaOYkOgkXlVqWy+kMPjRR/RhUXZmcHi/4JcLa9F8dZSr5X7M8aWLMi3ro3HscdL+acfr2YlDqUyBDSmXs9GCNtedazitUHTkPz/+p/gicKaHBri/RDz23zBTIckWrIJUL0jrCmkPBUcsHlBDcqesJktGKt61h328oFnl+2RrazfNFAjdjDykriyIZetuxdhZyNHLUeVhfX3BZsMK/0O4QMsnQ5qzYkXpxWUTzhwMVOT8tlz48zbDOW4d8q/sMxM/1LXme8eZeFIMFJfO6olJm+jbrnlqZAzTbaMuGeo1TyDgXLOS2dNijfDi4zGLqgqo4g1qYk0rOvT/hJtKXEKNEDO6QR9J7Hdyxu9bYmXcYJmYdN1O6GZ3z++y/KM0N/C1fnlpVNq8GKqGKRYqBY9H5EkTWl4a2pVPIRVkOVMBl6tu/LAuzVIZqT/GcAUxFMyKYt4ciDOO0e2xEordoSpKR19Z2J6meyyKr0gQQlM3pcOmMj2XRjysiGFRdNC/zBo1lkj2Kic7lHWt8x3ao57Lwgc1/JJTUk2Vn4FDr+n8EQcPEtD0yd/tLG8lQNClm+sPt3/YyKrnC/vNxH70Q9Sdbj/od9WtUrU3h8G2U9fV3RKMAz6gXGyMHN/MP7lr39OBFxXgJd3wp+yylJIyD1f2wdtHB/5oNabLYxuBRMAXkEeXT6BYrUyz2slnSVk=,iv:fDMUNGyKM8NgRQU0lhPXwoDm2sG58eYO/gBS9k3VkuI=,tag:92h0pAbcDzTZy/YwVmV3og==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzRoTXVyM2dmckpzbjJ3
        ZDIzVVZ0ckMyeDBnVmF3TDhQTzFMWEJLcHdvCldXamRuU3RrbkpWdDRhYi91NzhS
        em1OSS9DMC9OOHNVSzhYZjl4c3NMbmsKLS0tIFYwOFNPTEZtSWYwdHR4NzYvdW0w
        U1VrWW5WbjFPTWxNUXhpMEhpaHFqODgKnIqMqGkHepOITIDt4+bMNyxvrvwAE+F0
        fRO+gdo6v1WP1IBvUr4H3/hPaCeDs8aE3dnsRx6hr9A+uT/97vYBZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T18:11:28Z"
  mac: ENC[AES256_GCM,data:qcsUYhEr0razwFYtgLw3gIZYxzFh6SoevSibUy20BxoRKiXjbh4jqmQmG8nsINwOXs4Gz8LuuvFxUGUbRxmDfhoAeJA770FyUIoJFaHYAvURsVBSPsdf4hrsVnd/I+gmDV2gsvd1+aj+LBfiZpW+RvT7uwE2nUWnYPJ5Alj/uJw=,iv:nsUxnRdWkfvPmNa+ANK8D/TdstFbdr9PuIN+paNhYaI=,tag:HWe70ywo8+UHVTDuAYNNXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
