apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  slskd.yml: ENC[AES256_GCM,data:QWPRZAt7OzyeggRz8zdcv211rUBKRSqYRLUNvBnbwzkRNtA51RGbHMfyOPMdJbZvfp8K4h0/ozsxl8qJxSNodO1lSykGQZGibOJaaHevo4NhgUny78aUhNpswYIqC1vEbpv/35Hav0y6sjvg+5PLwZlj41lLhhBGYxKoJwla8G3dhpHdCrgfGauyrRz4rKSsHrN4rWcYa0KJWnjYb0611KNwu3CPFaL7tBHpHpyzKeCLhBDNnH8nq90te7E3q4efTu2zVvKR2y1LY3D5qFlutV1simYGTa3izg4z65ViO0GtORG26/LSm8VMeX3Oz57Wq9cSh107nt+HJIr3ekjyChHqn09zHeElKLf4Y127DZIz0Fw1ixGYUMfRvRNHOLFI3EPBToDLV6Xg0HNB+5X5eO47SNcxlJuI/lpGFUsvcEkj+uZJQuzu3em3IDb5o4cSwITdVz3L0SnVaE4uI+F9utN9OU8Oyt4F6Nw83je383xeDLAdUQDNscq42TFsw4W2EMKRaeP+1p9+sqIUIz3wD2od22m/kbX0WX5oNKdYTYN2WiXKMzniFjtjFzSFu0aH1SfGwcaBNflOkfTNwAF8hA8eEoCnYt6mhIwJNtmHtKYSA99pa6ilNz58vmziYrmncpjptd4af4G8iUOcd+/uB4rANLZoDH9FrdB6ThhFJ3TUbAycxKGHh67a8XoGcKQEhOud/l2rOPzeDQy6mkSR1rGeNAi3dD9jEM95zyY=,iv:+/HBjGqS284sj+/uxsT89bEjWL/iESUtTKU/6+Zkses=,tag:QJWP739C89JsqXA0KTaNxg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U1EwVW1sQzRsRlJYTk5a
        VWU4blAzb1VEelMzMGg4RzRmWUZMYW9JRERFCjFCUFFJSlhQOURmcXZKUkM4anVj
        U01YaGIvdVZmN0J3OGwxbGZkWkFEWTAKLS0tICtzN3pFZ3MzR25sRU9oNzA0NXdm
        MGliVWtZcXhyK1JzOFVmK1NzWlFpcjQKOZFreOlhPAIRLCSyCZB0+tkLMZ5LKHtI
        WBK/zHhsJdNxsebdGLku6mtPb5psUTXmROnY9X+P7ColeMk0U5fUyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T08:35:06Z"
  mac: ENC[AES256_GCM,data:VSwujHau2ddd25hTChbeAjEqcQOyPncGzmnZj0PCF9O/XQb8O3JhL7W3woZp81TWyGFCQIUo/pBCsbqRNvXf7DRoE6LHZUW0AahL9zh170/5gJMTNTTiKaTrYh5wxtJkJbrZ6Y0QhO5dKWCO6OWFIAuUAcGjG5YX22IPxMWHWS4=,iv:Q0sD6GPMvOkawt9oNWRMO/ruK0mHHafmoDNaUmSLVFo=,tag:CoLqwwt5sh+D7dMTcwXZYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
