apiVersion: v1
kind: Secret
metadata:
  name: cross-seed-secret
stringData:
  CROSS_SEED_API_KEY: ENC[AES256_GCM,data:aXUsrgTzKLec2+qxNIiDAnwce24HgIKLglb7p5pB+3s=,iv:iq8TE9WtJkXLUMpAuK9h+aaXA0GAm1eLSDpr0gefYcs=,tag:KiVKfBXrWS9EPkf+tSMoxg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSXNGM3dsWmwzVDd6emQw
        ZHhZVjZ1b2pmMXhjM1NVVE1GRzJKYnRuY1JvCkl4eUJtTGRBcjQ0ZXpyMEx1UTBZ
        NFJmbzdJRk5uYVVnUkdHNVBBRW12UXMKLS0tIDNBVmlQV2k2MUZrNGM5RytwN1Nr
        a2pvS2p4akpDZ2d6OUpKaW5NdGEvaFEK2eDyO+xxbLRroxOyC/jLPNOE3/+rVUE5
        t27XESGe7jRz7xgRQf2Sx/ITwf/mxEdgpgYqE6LVqvmhvO4JUEovBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T12:36:06Z"
  mac: ENC[AES256_GCM,data:iI16VyJKlZTxBXRZIflaffeLUcxTjWHKTlkyIU4HMcl/c1s2QyNzLcSc1+2IIZvt8gdM2lhXQaf2b15N7odmQ8Y5oZOQhZ4eMV8MpKcuNzuk4WhXDP4JJIXm7/5OhPLk28lyMzZsKJxUSBTf3Ig9D88O+EgjHdto7+RPQYZZ4gA=,iv:KTplkOJWx6A4fALLXWD0ngHYuJD0AdmLlZYCnQDXw4I=,tag:+HEIo2y2YETH0ItZ/yKohA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
