---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cross-seed
  namespace: flux-system
spec:
  components:
    - ../../../../components/keda
  interval: 1h
  path: kubernetes/apps/media/cross-seed/app
  prune: true
  postBuild:
    substitute:
      APP: cross-seed
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  dependsOn:
    - name: qbittorrent
    - name: prowlarr
