---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-dns-openwrt
spec:
  groups:
    - name: external-dns-openwrt.rules
      rules:
        - alert: ExternalDNSOpenWRTStale
          expr: |-
            time() - external_dns_controller_last_sync_timestamp_seconds{job="external-dns-openwrt"} > 60
          for: 5m
          annotations:
            summary: >-
              ExternalDNS ({{ $labels.job }}) has not synced successfully in the last five minutes
          labels:
            severity: critical
