apiVersion: v1
kind: Secret
metadata:
  name: external-dns-openwrt
stringData:
  PROVIDER_OPENWRT_LUCIRPC_HOSTNAME: ENC[AES256_GCM,data:U7/SQNiAp34rUfg=,iv:6OWYXpBkMzENbWQ0ZIYDxUkFXK+YEI8lgYI6d+XARs4=,tag:MZw4QwMJ3KH8af68BXEONA==,type:str]
  PROVIDER_OPENWRT_LUCIRPC_PORT: ENC[AES256_GCM,data:9gM=,iv:kKdUdFCFInv+co7MGzoxB6fD0ZYVuz61+iYCLrM3LZ0=,tag:wyJgxnlpwU4TV46zR24X2Q==,type:str]
  PROVIDER_OPENWRT_LUCIRPC_SSL: ENC[AES256_GCM,data:eVT4BDk=,iv:O3fNsre9f8WhkxF8eF5aEVWK+WnlnyMi8xw9qHedavI=,tag:EVheppyqc6dMWWOnZ/kckA==,type:str]
  PROVIDER_OPENWRT_LUCIRPC_AUTH_USERNAME: ENC[AES256_GCM,data:JfxThg==,iv:P/Mxrn04KaDeFpAEfkzFNsHUBDYYy4E4pJydLo9/a3k=,tag:B6ZerxO5L/XsE4Y7fbSZWQ==,type:str]
  PROVIDER_OPENWRT_LUCIRPC_AUTH_PASSWORD: ENC[AES256_GCM,data:Z3qr2SFICHY=,iv:a3TWz0cvsJPReJNLZb/ett7bpa1lVjZ+kMAhM5wO/dk=,tag:gMaxG/AaEvqY6WB9xd+dIA==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFJzUm4xQWtsL3dQcjM5
        Qk4yU2Z6TjArcytRWHUyalBpTHZiTWNpbVVBCkM5OGdlVW94NGJRUEV0alNrMzFH
        Wm9VTi9yNVp2M3ExZHZjd08xaExBVlkKLS0tIEhaOXk4NTY1ODlNSmdQOHp4SUpT
        eU9KTWZ5ZkFuNjR6RTJiVFV6TGVNL00KmAc0FaBGSUgZz0lqmumoBDEWhzQsydEw
        d7axAWAfi9fe83rOYKwvOzxYO6Qhgjrjq2CAl1Alx2lgtdUvBghCww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T20:40:41Z"
  mac: ENC[AES256_GCM,data:9JkkxytO40p0ooPNO6HdtDLa3yrtet+IwfH6ejVeaqOXTieuAY7FHYrHRF3mI5uVBqgr0Y3nn5QGNwduamkPkwBw7rNs0rCWkfQyv0CSChD87Bm9YgSjc6P0bK1mjrDJQpf9zQICp5kAj3ZkibXaCmBbch/zbZQZ5eoifw7C7JE=,iv:OjMuEMhydXEfZuFPlgw5Zom6XDnvTuis4aNfQxqpP+4=,tag:ILJSZRHaSDN9Q8D4otSuoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
