apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-restic-secret
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kxqP4N0m7tQs5A3FiI0jgz/kcQAL4F6FH2SiCc1hSTOE0aADvfHEI+NXpUrU,iv:zpT5DTcWfLlSXRq4ytiwOZJmxwedCbqY92dQf1Sh2jc=,tag:nHNYuow+h5DLZCaEK5rdGg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:awSngHvDGMRWqI4cdpo=,iv:soLQDIL4D4i0GpMWQYr8lUhonmnPkKS3ZtprmI0R0tI=,tag:0QgA0HV74DmamwBvXCaX1w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CgY91VwONJIQT67j6Pt1rLpOf0c=,iv:mWNYHLmzxLpUtM9YApwag1K6A/8bG7ZZ8nMBrhVs1vc=,tag:9awzIn7EOcEaLU/fCLcVNA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dymp0njChCCFjxjt5OejGL2bvvIKcpq7UuQC7VS7ooc+e0ll0ByL+A==,iv:q9khgOrHBL4dYsj3a9maaSaoDOBLS0b399G0OFOXJ7I=,tag:BNnzRApUuqZN8NbM2UVamw==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UDhiem1nUzVkMTlNc0Jo
        Nk9walJsVG9pWU42Ykg4M3hCUHJRYmFwSGdFClc4ZEdMT0VoR0EwNUZYTmVYM3lj
        VDVla3VMaGFHcWtqbkpPMnh2VnVYMlUKLS0tIHJIb2NYSkRNZm9CUm1ERGVVRjdC
        ZTg4enA2MHRaSVBHU09NTUZMSGplSnMKGBNOO9kC1iO1+8u4CkAxGChyL8VG8d/7
        nZG5UjDKjlxfkBOeT5b405aNMw44DGRx23r8I6if3fspH0RCpBNQlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T19:23:01Z"
  mac: ENC[AES256_GCM,data:pB4S+4ozUKy/OU8mlnH6lW/vjkko7oIuJ856dXTrscZezpcTGlqRwkZiIePRNcUQAwR16mrF2eBDsdGpo0a32BmM2nFOS7unkDSeNvZCaIgSz6l1u1UuGB3l5ngNvgGobK+cJLjtatcVElY0GCYw5Xhaft/+B15piJfxQq8eHAA=,iv:dos4snxhtAxuHnTbdpoJDR/HXDT+nIAU/S8kSmIyXsY=,tag:q56b8Lf9MpHiYKXcsGjbNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
