apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
stringData:
  LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:ieKRCrI3SttTO3JOMpsRErM2m+Ots/ho0QTGAYzcdOk=,iv:edilFTxgbpLyBi+vYNEiJHCfAnu9tSmAGrnuRAllHrk=,tag:RVXuEvTDFYr/bdtL60J9Vg==,type:str]
sops:
  age:
    - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjZnYXVCeDNRd2xTTUZB
        STVlS3pNMTltZmREV0J6NTJ1QTJrcVpDaFUwCmV5aUlSZFBsNXZBdk15R0dUVnpv
        WVZIUUM2VVhEZ1JOV1JqVEhxdDhVWEUKLS0tIHdmVllRNmpZZ1o5cEdnbncyNno0
        VkNkUHpyYmxaNVZUcS84T3BPNHo1MEEKQ68RnrwhFZAEHPu3nCDJk1dnF63hON1I
        z1l+BHk1xdFwRA0qw0h0cWOPc2UVDZC+XeTZMWIMO3LhWyYwU0pK3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T14:56:47Z"
  mac: ENC[AES256_GCM,data:6rrPI5v/N5hCfdB+rDJFgtnh5OvSPLfVuHtpUus22ImXj2Pnft/W7Hnn0qtIHKpShvRreAzRWUfs8YdywX39qDeJDmZ3ekMZqeQCE6woT6N3VoBt4VqxaizGx68+adjDHmPzbcTMrvO+3Cl9bygIqUhrVHGevoxRdJNZUnqBmVE=,iv:pqjwhMdjaIi3IXgHsMT8c1i+tvZTf7D5gEGx8AhxjDQ=,tag:BYdEeEbTgyX9T7tKMHfXzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
