---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tf-controller
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.16.0-rc.6
  url: oci://ghcr.io/flux-iac/charts/tofu-controller

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tf-controller
spec:
  chartRef:
    kind: OCIRepository
    name: tf-controller
  interval: 1h
  values:
    fullnameOverride: *app

    allowBreakTheGlass: true
    allowCrossNamespaceRefs: true

    installCRDs: true

    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    #     endpoint:
    #       interval: 1m

    runner:
      serviceAccount:
        create: true
        allowedNamespaces:
          - media
          - security
