---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production
spec:
  commonName: ${CLUSTER_DOMAIN}
  dnsNames:
    - "*.${CLUSTER_DOMAIN}"
    - ${CLUSTER_DOMAIN}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: production-tls
  usages:
    - server auth
    - client auth
