---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble
spec:
  parentRefs:
    - { name: internal, namespace: kube-system }
  hostnames:
    - "hubble.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs: [{ name: hubble-ui, port: 80 }]
      matches:
        - path: { type: PathPrefix, value: / }
