---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - gateway-class.yaml
  - gw-external.yaml
  - gw-internal.yaml
  # - gw-passthrough.yaml
  - httproute.yaml
  # - redirect.yaml
