apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:LEEkkqJx0Ps=,iv:4k+rd3xh9ZDPty+lb2wUCGLCEePQANFgF45m8uv5Rq8=,tag:2fzeYJAVfkYhUb6B6JSuuQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Gp0MOUZurIzokGGsWnQ=,iv:aEUPWDpCTaTl+E3rITRLVn6rtizazKUZkZmtUijP8qg=,tag:YgKTF8kULKMUSiJ+oMkxRA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:cd6SxDI0X3NKKwl+zFzByWclZW5zuUYAoCqOETN9SmlnbJXP6RyiJbAh3Q==,iv:2i0tn1Jr5u6ua2ms0QZDFb75WfbX7XsoWvWKGeY3gJw=,tag:FoLDGCSpKEXJIkb4GISYbg==,type:str]
    PAPERLESS_APPS: ENC[AES256_GCM,data:dh42oICjmHPX3GZN4jN4RDocy89HP4uN6SewwKR7VhBKK1kycFXldi0IvQ1hKw==,iv:A9oPdK1f7fhKBeFvIzNROkUn5SGxAScZfY35H1FfxGo=,tag:fDYeFx+SBcbVqNCcoujDUw==,type:str]
    PAPERLESS_SOCIAL_AUTO_SIGNUP: ENC[AES256_GCM,data:aYpdgg==,iv:QKu9Vi0vfurLYXFfwqGWa8GxruT5GMwGkFZx2NK0ZLY=,tag:8vhrNdKuEI17XE+0znPvqw==,type:str]
    PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: ENC[AES256_GCM,data:UJ0Xrg==,iv:m34ndiO+Ngd807g/Va+/lJe0e65SkbKp+9PJekFLP4g=,tag:Mvqv6Zgh704N6MaUTNShOw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:CQTfkdzFOwbqFRQG+M5o+WQYwqwEGbg+5pEIn/Q9k0svmFFoAByMTIInoFodWDZm6R2LzGjBvBG0DYmJOf+hSJxk+J6Go2Y6wawCm41MFMmcg0w+UF4Ha30l2Vmoxibq6UH+gGRE4w60eJPh2pZWKvCne4T4V/A18WkTMBLfm5HuHc0Gc/yAXrzIDK6IQ/zShNDyZ/p3dcGqQrLt2l4hFg89TVk6Eaq52/7a1bUnnzNF5skbAiM3nu7bCwFNw1IlOK4E2+EAiNtcqT7Ntg6wpmag94LKkX+355ZJhK496mmvUw4JqsSoqBMI2rit9Pw+FjsGZMo9Apq+JgQL+I2BWObyNlEDDFthT4bvg49emJusrk7G8QOO2KhNrfGkOUwTWdg31fBDxmglD5mgAZmuiOQw8VcDvH3o7T/tVIowsZNPQ8x3mIdhcJTlCqsjxv2h1aPb67vQj88kCVZebvk4Wjv70L+6sOeuZdvhfBLN5wUnPn6CI5N3Wqqb/v2EEoNEwM8u2q0xhZDk+w2v7L24ZCu6f55rZ2vGtyfMqD1WrbJrqQv72F2G9wY7iXZUAd4cQ7TGsDnV8G22lb13wvs56mSCKa3N7mQH0eD4fzGdCE6w4dZuaHvxodReUPuOAu5yKCKu/Qe6PzfPunvhK8MVluPc3DcEdMA60aLJ7+Tjz3Si0ZV33NPRM2eprFhfnIBT9q0L7VWPe9tF8xxJFBKsiRUH8BIcCC6RjMrjXJV5hS7DP8Oc2nhzhV/zmTzap8s9xMYdiheUhsSeV5KhXCERXfnfbDqyxftBsuRuc8MKbRfZMOaGRLDCPf3AE1oGUNLJQAcCrdiRIkHicZvzh+Eq3ZgK9r8sayftI2w+YCOUB4hlmFALUwMpurfpkSvVE2hJIHISz/Z33sYXMgyh321F/u3F2uo1mpyUWy7DotiKhhK2g2VohpKlgRbI640vo1A+TowYKf8HQHByQYcrAKFSYLz8Sl7V8jDIdTjWTAphx7TmoVHjfouDcA==,iv:yadbalZoi2+c7TWolP/ZeqUIqDEi+RQrQ0muanbkNKY=,tag:XWG45/Ni/5sdAPx5zmwBqQ==,type:str]
    PAPERLESS_LOGOUT_REDIRECT_URL: ENC[AES256_GCM,data:1GdOqhUz0Rhce7mTZouvMRIEkbmPep0kPqqUizE9EVvQQAlMhX/nsekvx9ohjS0VlGe1kEaoGWb/lh4g6L9sh7EspzE=,iv:0AemC/FbaDspN1euRpVWc1WtfpscCB914tKo1VYHavM=,tag:RCfDRNx9mVLoyQl0UQkXiQ==,type:str]
    PAPERLESS_AUTO_LOGIN: ENC[AES256_GCM,data:4A48iw==,iv:LJWFGZzMO8pXM6MhtFMQRWV88QQEkS89WS3V60wBCkA=,tag:QAc0Fah66p92nSoZjO0axQ==,type:str]
    PAPERLESS_AUTO_CREATE: ENC[AES256_GCM,data:bLjC/Q==,iv:t4SlA1wSke3CaEhy2I8A5/nhkMj7kGnT7d+IPZeWsVk=,tag:92Hqzle9OzoEK7JfH/9BIA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb3RXeUo2czZCZGZPaDlN
            cUxiUFFHZkEybDJ0alpmWXVVbm5HdENOb0dNCkkzNzRhQUF1K1AxYUZZOWFsUyt0
            cXA5RzhwclNOT1p3N2RtamExcmRtWGMKLS0tIHVUSytDWHNtaG1kQ0hDUkhYcWZu
            YmVqZFc0cVpSNWIreXM3NHM2cGRmOTAKifsTWFeGeasD2hKGoT4Kd3aMF/ogwtPq
            6M+3TE/sTvNVBwHR+4aGjzxHIV0VymbWV7iCAfDuikwC1GU9YEMBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T19:11:25Z"
    mac: ENC[AES256_GCM,data:vKwaLyRQI4Jt22rnDtNEsc17WZph6dTcU/9DrkwWFiTtCDlyCXLr+0tHgmKk90Jc6EBpYN21/LmYkZgxGvF4AtRdFu27QdFo2cUAxyRMfTUMFszbjxyvoyQIx1legX80GBV7WABytPpVHAWqiB/GTN4/9aKzzm6O2BHmswvliaU=,iv:p+spXHu3XiO54N8BWg0XscpDFyJnhJ7GkQunZTEC9Y0=,tag:tWiZAyKZ3pCxfbH3639xkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
